function paramMap_GUI()
% paramMap_GUI - Interactive viewer for automated QVT+ outputs.
%
% This tool lets you inspect the results generated by paramMap_auto.m.
% It loads the processed QVT data, reconstructed eICAB correspondence, and
% automatically selected LOCs, then launches a lightweight GUI to explore
% the vasculature, isolate vessels, and visualize LOC positions.
%
% Usage:
%   >> paramMap_GUI
%
% The script will prompt you to select the output directory created by
% paramMap_auto (the folder containing qvtData_ISOfix_*.mat, SummaryParamTool.xls,
% multilabel_QVTseg.nii, etc.).

    outputDir = uigetdir(pwd, 'Select a QVT+ output directory');
    if isequal(outputDir, 0)
        disp('paramMap_GUI: No folder selected. Exiting.');
        return;
    end

    matInfo = dir(fullfile(outputDir, 'qvtData_ISOfix_*.mat'));
    if isempty(matInfo)
        error('paramMap_GUI:MissingData', ...
              'No qvtData_ISOfix_*.mat file found in %s.', outputDir);
    end

    % In case there are multiple processed files, pick the most recent
    [~, newestIdx] = max([matInfo.datenum]);
    matFile = fullfile(outputDir, matInfo(newestIdx).name);

    dataVars = load(matFile, 'data_struct', 'Vel_Time_Res');
    data_struct = dataVars.data_struct;
    Vel_Time_Res = dataVars.Vel_Time_Res;

    % Rebuild correspondence dictionary and LOCs from outputs on disk
    try
        [correspondenceDict, multiQVT] = generateCorrespondenceDict(outputDir, data_struct);
    catch ME
        error('paramMap_GUI:LabelFilesMissing', ...
              'Unable to rebuild correspondence dictionary: %s', ME.message);
    end

    [correspondenceDict, LOCs] = generateLOCs(data_struct, correspondenceDict, multiQVT);

    % Filter LOCs that do not have the expected [segment, idx] structure
    locKeys = fieldnames(LOCs);
    validLocMask = false(size(locKeys));
    for iKey = 1:numel(locKeys)
        entry = LOCs.(locKeys{iKey});
        validLocMask(iKey) = isnumeric(entry) && isvector(entry) && numel(entry) == 2;
    end
    locKeys = locKeys(validLocMask);

    if isempty(locKeys)
        warning('paramMap_GUI:NoLOCs', 'No LOC entries detected.');
    end

    locInfo = computeLocInfo(locKeys, LOCs, data_struct);

    vesselNames = buildDisplayNames(locKeys);
    paramOptions = createParamOptions(data_struct);
    cmapList = {'parula','turbo','jet','hot','cool','summer','autumn','winter','gray','bone'};

    app.figure = figure('Name', 'QVT+ Viewer', ...
                        'NumberTitle', 'off', ...
                        'Color', [0 0 0], ...
                        'Units', 'normalized', ...
                        'Position', [0.08 0.08 0.84 0.82]);
    movegui(app.figure, 'center');

    app.axes = axes('Parent', app.figure, ...
                    'Position', [0.05 0.32 0.6 0.63], ...
                    'Color', 'k');
    hold(app.axes, 'on');
    axis(app.axes, 'equal');
    axis(app.axes, 'off');
    view(app.axes, 3);
    % rotate3d(app.figure, 'on');

    % Try to load multilabel volume for colored isosurfaces
    multilabelPath = fullfile(outputDir, 'multilabel_QVTseg.nii');
    if exist(multilabelPath, 'file')
        try
            V = spm_vol(multilabelPath);
            multiQVTvol = spm_read_vols(V);
        catch
            multiQVTvol = [];
        end
    else
        multiQVTvol = [];
    end

    % Load auxiliary TOF overlays if present
    tofPath = fullfile(outputDir, 'r_TOF_resampled.nii');
    tofVolume = [];
    tofMat = [];
    tofThresh = [];
    if exist(tofPath, 'file')
        try
            tofHeader = spm_vol(tofPath);
            tofVolume = spm_read_vols(tofHeader);
            tofMat = tofHeader.mat;
            voxValues = tofVolume(isfinite(tofVolume));
            if ~isempty(voxValues)
                pLow = prctile(voxValues, 70);
                pHigh = prctile(voxValues, 99.5);
                if pLow == pHigh
                    pLow = min(voxValues);
                    pHigh = max(voxValues);
                end
                tofThresh = [pLow, pHigh];
            end
        catch ME
            warning('paramMap_GUI:LoadTOF','Failed to load r_TOF_resampled.nii: %s', ME.message);
            tofVolume = [];
        end
    end

    atlasPath = fullfile(outputDir, 'r_TOF_eICAB_CW.nii');
    atlasVolume = [];
    if exist(atlasPath, 'file')
        try
            atlasHeader = spm_vol(atlasPath);
            atlasVolume = spm_read_vols(atlasHeader);
        catch ME
            warning('paramMap_GUI:LoadAtlas','Failed to load r_TOF_eICAB_CW.nii: %s', ME.message);
            atlasVolume = [];
        end
    end

    [surfacePatches, scatterAll, scatterSel] = plotCenterlines(app.axes, data_struct, correspondenceDict, multiQVTvol);
    locPlots = plotLocMarkers(app.axes, locInfo);
    cursorMarker = scatter3(app.axes, NaN, NaN, NaN, ...
                            160, [0 1 0], 'filled', ...
                            'MarkerEdgeColor', 'k', ...
                            'Visible', 'off', ...
                            'HitTest', 'off', ...
                            'PickableParts', 'none');
    planeLines = gobjects(4,1);
    for iLine = 1:4
        planeLines(iLine) = plot3(app.axes, NaN, NaN, NaN, ...
                                  'Color', [1 0.25 0.25], ...
                                  'LineWidth', 1.6, ...
                                  'HitTest', 'off', ...
                                  'PickableParts', 'none', ...
                                  'Visible', 'off');
    end
    planePatch = patch(app.axes, ...
                       'Faces', [1 2 3 4], ...
                       'Vertices', zeros(4,3), ...
                       'FaceColor', [1 0.2 0.2], ...
                       'FaceAlpha', 0.5, ...
                       'EdgeColor', 'none', ...
                       'Visible', 'off', ...
                       'HitTest', 'off', ...
                       'PickableParts', 'none');
    planeNormal = quiver3(app.axes, NaN, NaN, NaN, 0, 0, 0, ...
                          'Color', [1 0.45 0.2], ...
                          'LineWidth', 2.0, ...
                          'AutoScale', 'off', ...
                          'HitTest', 'off', ...
                          'Visible', 'off');
    planeNormalTip = scatter3(app.axes, NaN, NaN, NaN, ...
                              40, [1 0.25 0.25], 'filled', ...
                              'MarkerEdgeColor', 'k', ...
                              'Visible', 'off', ...
                              'HitTest', 'off', ...
                              'PickableParts', 'none');

    colormap(app.axes, parula);

    % Compact UI layout - Group 1: Vessel and Parameter selection
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.66 0.94 0.15 0.022], ...
              'String', 'Vessel', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    dropdownList = [{'All Vessels'}, vesselNames(:)'];
    dropdown = uicontrol('Style', 'popupmenu', ...
                         'Parent', app.figure, ...
                         'Units', 'normalized', ...
                         'Position', [0.66 0.91 0.15 0.028], ...
                         'String', dropdownList, ...
                         'BackgroundColor', [1 1 1], ...
                         'FontSize', 8);

    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.82 0.94 0.14 0.022], ...
              'String', 'Parameter', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    paramDropdown = uicontrol('Style', 'popupmenu', ...
                              'Parent', app.figure, ...
                              'Units', 'normalized', ...
                              'Position', [0.82 0.91 0.14 0.028], ...
                              'String', {paramOptions.label}, ...
                              'BackgroundColor', [1 1 1], ...
                              'FontSize', 8);
    paramDropdown.Value = 1;

    % Group 2: Colormap and Colorbar limits (compact)
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.66 0.87 0.08 0.022], ...
              'String', 'Colormap', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    cmapDropdown = uicontrol('Style', 'popupmenu', ...
                             'Parent', app.figure, ...
                             'Units', 'normalized', ...
                             'Position', [0.66 0.84 0.08 0.028], ...
                             'String', cmapList, ...
                             'BackgroundColor', [1 1 1], ...
                             'FontSize', 8);
    cmapDropdown.Value = 1;

    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.75 0.87 0.05 0.022], ...
              'String', 'Min', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    cbMinEdit = uicontrol('Style', 'edit', ...
                          'Parent', app.figure, ...
                          'Units', 'normalized', ...
                          'Position', [0.75 0.84 0.05 0.028], ...
                          'BackgroundColor', [1 1 1], ...
                          'FontSize', 8);

    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.81 0.87 0.05 0.022], ...
              'String', 'Max', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    cbMaxEdit = uicontrol('Style', 'edit', ...
                          'Parent', app.figure, ...
                          'Units', 'normalized', ...
                          'Position', [0.81 0.84 0.05 0.028], ...
                          'BackgroundColor', [1 1 1], ...
                          'FontSize', 8);

    % Group 3: Isosurface transparency control
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.87 0.87 0.09 0.022], ...
              'String', 'Mask Alpha', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    alphaSlider = uicontrol('Style', 'slider', ...
                            'Parent', app.figure, ...
                            'Units', 'normalized', ...
                            'Position', [0.87 0.84 0.09 0.028], ...
                            'Min', 0, ...
                            'Max', 1, ...
                            'Value', 0.3, ...
                            'SliderStep', [0.05 0.1]);

    syncCheckbox = uicontrol('Style', 'checkbox', ...
                             'Parent', app.figure, ...
                             'Units', 'normalized', ...
                             'Position', [0.87 0.80 0.09 0.028], ...
                             'String', 'Sync Masks', ...
                             'Value', 1, ...
                             'ForegroundColor', [1 1 1], ...
                             'BackgroundColor', [0 0 0], ...
                             'FontSize', 8, ...
                             'HorizontalAlignment', 'left');

    % Group 4: Action buttons (compact)
    focusButton = uicontrol('Style', 'pushbutton', ...
                            'Parent', app.figure, ...
                            'Units', 'normalized', ...
                            'Position', [0.66 0.80 0.10 0.028], ...
                            'String', 'Focus LOC', ...
                            'FontSize', 8);

    resetButton = uicontrol('Style', 'pushbutton', ...
                            'Parent', app.figure, ...
                            'Units', 'normalized', ...
                            'Position', [0.77 0.80 0.10 0.028], ...
                            'String', 'Reset', ...
                            'FontSize', 8, ...
                            'Callback', @(~,~) resetView(app.figure));

    % Group 5: TOF / Atlas overlays
    tofCheckbox = uicontrol('Style', 'checkbox', ...
                            'Parent', app.figure, ...
                            'Units', 'normalized', ...
                            'Position', [0.66 0.76 0.12 0.026], ...
                            'String', 'Show TOF overlay', ...
                            'Value', 0, ...
                            'ForegroundColor', [1 1 1], ...
                            'BackgroundColor', [0 0 0], ...
                            'FontSize', 8, ...
                            'HorizontalAlignment', 'left');
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.79 0.76 0.05 0.024], ...
              'String', 'TOF Min', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    tofMinEdit = uicontrol('Style', 'edit', ...
                           'Parent', app.figure, ...
                           'Units', 'normalized', ...
                           'Position', [0.79 0.734 0.05 0.028], ...
                           'BackgroundColor', [1 1 1], ...
                           'FontSize', 8);
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.85 0.76 0.05 0.024], ...
              'String', 'TOF Max', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    tofMaxEdit = uicontrol('Style', 'edit', ...
                           'Parent', app.figure, ...
                           'Units', 'normalized', ...
                           'Position', [0.85 0.734 0.05 0.028], ...
                           'BackgroundColor', [1 1 1], ...
                           'FontSize', 8);

    atlasCheckbox = uicontrol('Style', 'checkbox', ...
                              'Parent', app.figure, ...
                              'Units', 'normalized', ...
                              'Position', [0.91 0.76 0.10 0.026], ...
                              'String', 'Show Atlas', ...
                              'Value', 0, ...
                              'ForegroundColor', [1 1 1], ...
                              'BackgroundColor', [0 0 0], ...
                              'FontSize', 8, ...
                              'HorizontalAlignment', 'left');

    % TOF transparency control
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.66 0.70 0.08 0.022], ...
              'String', 'TOF Alpha', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    tofAlphaSlider = uicontrol('Style', 'slider', ...
                               'Parent', app.figure, ...
                               'Units', 'normalized', ...
                               'Position', [0.66 0.67 0.08 0.028], ...
                               'Min', 0, ...
                               'Max', 1, ...
                               'Value', 0.15, ...
                               'SliderStep', [0.05 0.1]);

    % Atlas transparency control
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.75 0.70 0.08 0.022], ...
              'String', 'Atlas Alpha', ...
              'BackgroundColor', [0.94 0.94 0.94], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    atlasAlphaSlider = uicontrol('Style', 'slider', ...
                                 'Parent', app.figure, ...
                                 'Units', 'normalized', ...
                                 'Position', [0.75 0.67 0.08 0.028], ...
                                 'Min', 0, ...
                                 'Max', 1, ...
                                 'Value', 0.18, ...
                                 'SliderStep', [0.05 0.1]);

    if ~isempty(tofThresh)
        tofMinEdit.String = sprintf('%.2f', tofThresh(1));
        tofMaxEdit.String = sprintf('%.2f', tofThresh(2));
    else
        set([tofCheckbox, tofMinEdit, tofMaxEdit, tofAlphaSlider], 'Enable', 'off');
    end
    if isempty(atlasVolume)
        set([atlasCheckbox, atlasAlphaSlider], 'Enable', 'off');
    end

    infoBox = uicontrol('Style', 'text', ...
                        'Parent', app.figure, ...
                        'Units', 'normalized', ...
                        'Position', [0.68 0.05 0.27 0.18], ...
                        'String', '', ...
                        'HorizontalAlignment', 'left', ...
                        'BackgroundColor', [0.2 0.2 0.2], ...
                        'ForegroundColor', [1 1 1], ...
                        'FontSize', 10);

    app.axesMAG = axes('Parent', app.figure, ...
                       'Position', [0.66 0.50 0.14 0.15], ...
                       'Color', 'k');
    app.axesCD = axes('Parent', app.figure, ...
                      'Position', [0.815 0.50 0.14 0.15], ...
                      'Color', 'k');
    app.axesVelTA = axes('Parent', app.figure, ...
                         'Position', [0.66 0.31 0.14 0.15], ...
                         'Color', 'k');
    app.axesVelTR = axes('Parent', app.figure, ...
                         'Position', [0.815 0.31 0.14 0.15], ...
                         'Color', 'k');
    app.axesWave = axes('Parent', app.figure, ...
                        'Position', [0.05 0.05 0.6 0.2], ...
                        'Color', [0.1 0.1 0.1]);

    setupCrossAxes(app.axesMAG, 'MAG');
    setupCrossAxes(app.axesCD, 'CD');
    setupCrossAxes(app.axesVelTA, 'Velocity (TA)');
    setupCrossAxes(app.axesVelTR, 'Velocity (TR)');
    prepareWaveformAxes(app.axesWave);

    try
        camlight(app.axes, 'headlight');
    catch ME
        warning('paramMap_GUI:CamlightInit','camlight failed: %s', ME.message);
    end
    lighting(app.axes, 'gouraud');

    cb = colorbar(app.axes);
    cb.Color = [1 1 1];
    cb.Label.Color = [1 1 1];

    appData.branchList = data_struct.branchList;
    appData.area_val = data_struct.area_val;
    appData.diam_val = data_struct.diam_val;
    appData.flowPerHeartCycle_val = data_struct.flowPerHeartCycle_val;
    appData.maxVel_val = data_struct.maxVel_val;
    appData.velMean_val = data_struct.velMean_val;
    appData.StdvFromMean = data_struct.StdvFromMean;
    appData.PI_val = data_struct.PI_val;
    appData.RI_val = data_struct.RI_val;
    appData.locInfo = locInfo;
    appData.correspondenceDict = correspondenceDict;
    appData.locPlots = locPlots;
    appData.scatterAll = scatterAll;
    appData.scatterSel = scatterSel;
    appData.cursorMarker = cursorMarker;
    appData.planeLines = planeLines;
    appData.planePatch = planePatch;
    appData.planeNormal = planeNormal;
    appData.planeNormalTip = planeNormalTip;
    appData.infoBox = infoBox;
    appData.axes = app.axes;
    appData.axesMAG = app.axesMAG;
    appData.axesCD = app.axesCD;
    appData.axesVelTA = app.axesVelTA;
    appData.axesVelTR = app.axesVelTR;
    appData.axesWave = app.axesWave;
    appData.selection = struct('key', '', 'locIndex', [], 'pointRow', [], 'selIndices', []);
    appData.paramOptions = paramOptions;
    appData.surfacePatches = surfacePatches;
    appData.alphaSlider = alphaSlider;
    appData.syncCheckbox = syncCheckbox;
    appData.tofCheckbox = tofCheckbox;
    appData.tofMinEdit = tofMinEdit;
    appData.tofMaxEdit = tofMaxEdit;
    appData.tofAlphaSlider = tofAlphaSlider;
    appData.atlasCheckbox = atlasCheckbox;
    appData.atlasAlphaSlider = atlasAlphaSlider;
    appData.colormapList = cmapList;
    appData.paramDropdown = paramDropdown;
    appData.cmapDropdown = cmapDropdown;
    appData.cbMinEdit = cbMinEdit;
    appData.cbMaxEdit = cbMaxEdit;
    appData.colorbar = cb;
    appData.dropdown = dropdown;
    appData.locKeys = locKeys;
    appData.vesselNames = vesselNames;
    appData.flowPulsatile = data_struct.flowPulsatile_val;
    appData.nframes = data_struct.nframes;
    appData.timeres = data_struct.timeres;
    appData.segmentFull = data_struct.segmentFull;
    appData.Planes = data_struct.Planes;
    appData.MAGcrossection = data_struct.MAGcrossection;
    appData.timeMIPcrossection = data_struct.timeMIPcrossection;
    appData.vTimeFrameave = data_struct.vTimeFrameave;
    appData.VplanesAllx = Vel_Time_Res.VplanesAllx;
    appData.VplanesAlly = Vel_Time_Res.VplanesAlly;
    appData.VplanesAllz = Vel_Time_Res.VplanesAllz;
    appData.imdim = sqrt(size(data_struct.segmentFull, 2));
    appData.data_struct = data_struct;
    appData.currentParamIndex = 1;
    appData.tofVolume = tofVolume;
    appData.tofMat = tofMat;
    appData.tofThresholds = tofThresh;
    % OLD CODE: tofPatch for isosurface rendering (commented out - replaced with volshow)
    % appData.tofPatch = [];
    appData.tofVolshow = []; % volshow viewer handle
    appData.tofWindow = []; % TOF window handle
    appData.showTOF = false;
    appData.atlasVolume = atlasVolume;
    appData.atlasPatches = [];
    appData.atlasLabels = [];
    appData.showAtlas = false;

    guidata(app.figure, appData);

    dropdown.Callback = @(src, ~) updateSelection(app.figure, src.Value, vesselNames, locKeys);
    paramDropdown.Callback = @(src, ~) changeParameter(app.figure, src.Value);
    cmapDropdown.Callback = @(src, ~) changeColormap(app.figure, src.Value);
    cbMinEdit.Callback = @(src, ~) updateColorLimits(app.figure, 'min', str2double(src.String));
    cbMaxEdit.Callback = @(src, ~) updateColorLimits(app.figure, 'max', str2double(src.String));
    alphaSlider.Callback = @(~, ~) applyMaskAlphasAndTOF(app.figure);
    syncCheckbox.Callback = @(~, ~) applyMaskAlphas(app.figure);
    tofCheckbox.Callback = @(src, ~) toggleTOFOverlay(app.figure, logical(src.Value));
    tofMinEdit.Callback = @(src, ~) updateTOFThreshold(app.figure, 'min', str2double(src.String));
    tofMaxEdit.Callback = @(src, ~) updateTOFThreshold(app.figure, 'max', str2double(src.String));
    tofAlphaSlider.Callback = @(src, ~) updateTOFOverlay(app.figure);
    atlasCheckbox.Callback = @(src, ~) toggleAtlasOverlay(app.figure, logical(src.Value));
    atlasAlphaSlider.Callback = @(src, ~) updateAtlasOverlay(app.figure);
    focusButton.Callback = @(~,~) focusOnSelectedLOC(app.figure);
    resetButton.Callback = @(~,~) resetView(app.figure);

    scatterAll.ButtonDownFcn = @(src, evt) onScatterClick(app.figure, src, evt);
    scatterSel.ButtonDownFcn = @(src, evt) onScatterClick(app.figure, src, evt);

    applyParameterSelection(app.figure, 1, true);
    updateSelection(app.figure, 1, vesselNames, locKeys);
    applyMaskAlphas(app.figure);
    updateTOFOverlay(app.figure);
    updateAtlasOverlay(app.figure);
    
    % Ensure scatter plots are on top for click detection
    appData = guidata(app.figure);
    if isfield(appData, 'scatterAll') && isgraphics(appData.scatterAll)
        uistack(appData.scatterAll, 'top');
    end
    if isfield(appData, 'scatterSel') && isgraphics(appData.scatterSel)
        uistack(appData.scatterSel, 'top');
    end
    if isfield(appData, 'cursorMarker') && isgraphics(appData.cursorMarker)
        uistack(appData.cursorMarker, 'top');
    end

    waitfor(app.figure);
end

function locInfo = computeLocInfo(locKeys, LOCs, data_struct)
    locInfo = struct('key', {}, 'segment', {}, 'clIndex', {}, ...
                     'rowIdx', {}, 'coord', {}, 'flow', {}, ...
                     'PI', {}, 'RI', {});
    branchList = data_struct.branchList;
    for i = 1:numel(locKeys)
        key = locKeys{i};
        entry = LOCs.(key);
        segID = entry(1);
        clIdx = entry(2);
        matchRows = find(branchList(:,4) == segID & branchList(:,5) == clIdx, 1);
        if isempty(matchRows)
            warning('paramMap_GUI:MissingBranchRow', ...
                    'No branchList row found for %s (segment %d, index %d).', ...
                    key, segID, clIdx);
            continue;
        end
        locInfo(end+1).key = key; 
        locInfo(end).segment = segID;
        locInfo(end).clIndex = clIdx;
        locInfo(end).rowIdx = matchRows;
        locInfo(end).coord = branchList(matchRows, 1:3);
        locInfo(end).flow = data_struct.flowPerHeartCycle_val(matchRows);
        locInfo(end).PI = data_struct.PI_val(matchRows);
        locInfo(end).RI = data_struct.RI_val(matchRows);
    end
end

function names = buildDisplayNames(keys)
    pretty = containers.Map( ...
        {'LICA','RICA','BASI','LMCA','RMCA','LACA','RACA', ...
         'LPCA','RPCA','SSSV','LTSV','RTSV','STRV','COMM'}, ...
        {'Left ICA','Right ICA','Basilar', ...
         'Left MCA','Right MCA','Left ACA','Right ACA', ...
         'Left PCA','Right PCA','Superior Sagittal Sinus', ...
         'Left Transverse Sinus','Right Transverse Sinus','Straight Sinus','Communicating'} ...
    );
    names = cell(size(keys));
    for i = 1:numel(keys)
        key = keys{i};
        if pretty.isKey(key)
            names{i} = pretty(key);
        else
            names{i} = key;
        end
    end
end

function [surfacePatches, scatterAll, scatterSel] = plotCenterlines(ax, data_struct, correspondenceDict, multiQVTvol)
    % Generate colored isosurfaces for each vessel
    surfacePatches = struct('handle', {}, 'label', {}, 'vessel', {});

    % Define distinct colors for each vessel type
    vesselColors = containers.Map(...
        {'LICA', 'RICA', 'BASI', 'LMCA', 'RMCA', 'LACA', 'RACA', ...
         'LPCA', 'RPCA', 'SSSV', 'LTSV', 'RTSV', 'STRV', 'COMM'}, ...
        {[1 0.2 0.2], [0.2 0.2 1], [0.2 1 0.2], [1 0.6 0.2], [0.6 0.2 1], ...
         [1 0.8 0.2], [0.8 0.2 1], [0.2 1 0.8], [0.2 0.8 1], ...
         [1 0.4 0.6], [0.4 1 0.6], [0.6 0.4 1], [0.8 0.8 0.2], [0.5 0.5 0.5]});

    % Use multilabel volume if available, otherwise use binary segment
    if ~isempty(multiQVTvol) && ~all(multiQVTvol(:) == 0)
        segVol = permute(multiQVTvol, [2 1 3]);
        uniqueLabels = unique(segVol(segVol > 0));

        % Map labels to vessel names using correspondenceDict
        labelToVessel = containers.Map('KeyType', 'double', 'ValueType', 'char');
        vesselKeys = fieldnames(correspondenceDict);
        for i = 1:numel(vesselKeys)
            key = vesselKeys{i};
            segments = correspondenceDict.(key);
            for seg = segments(:)'
                branchMask = data_struct.branchList(:,4) == seg;
                if any(branchMask)
                    coords = round(data_struct.branchList(branchMask, 1:3));
                    coordsPerm = [coords(:,2), coords(:,1), coords(:,3)];
                    validCoords = coordsPerm(:,1) >= 1 & coordsPerm(:,1) <= size(segVol,1) & ...
                                  coordsPerm(:,2) >= 1 & coordsPerm(:,2) <= size(segVol,2) & ...
                                  coordsPerm(:,3) >= 1 & coordsPerm(:,3) <= size(segVol,3);
                    if any(validCoords)
                        linearIdx = sub2ind(size(segVol), coordsPerm(validCoords,1), ...
                                           coordsPerm(validCoords,2), coordsPerm(validCoords,3));
                        labels = unique(segVol(linearIdx));
                        labels = labels(labels > 0);
                        if ~isempty(labels)
                            for lbl = labels(:)'
                                if ~isKey(labelToVessel, lbl)
                                    labelToVessel(lbl) = key;
                                end
                            end
                        end
                    end
                end
            end
        end

        % Create isosurface for each unique label
        for lbl = uniqueLabels(:)'
            if isKey(labelToVessel, lbl)
                vesselName = labelToVessel(lbl);
                if vesselColors.isKey(vesselName)
                    color = vesselColors(vesselName);
                else
                    color = [0.7 0.7 0.7];
                end
            else
                vesselName = '';
                color = [0.7 0.7 0.7];
            end

            try
                maskVol = (segVol == lbl);
                if any(maskVol(:))
                    fv = isosurface(maskVol, 0.5);
                    if ~isempty(fv.vertices)
                        patchHandle = patch(ax, fv, ...
                            'FaceColor', color, ...
                            'EdgeColor', 'none', ...
                            'FaceAlpha', 0.5, ...
                            'HitTest', 'off', ...
                            'PickableParts', 'none');
                        surfacePatches(end+1) = struct( ... %#ok<AGROW>
                            'handle', patchHandle, ...
                            'label', lbl, ...
                            'vessel', vesselName);
                    end
                end
            catch ME
                warning('paramMap_GUI:IsosurfaceLabelFailed', ...
                        'Could not generate isosurface for label %d: %s', lbl, ME.message);
            end
        end
    else
        % Fallback to binary segment with single gray isosurface
        segVol = permute(data_struct.segment, [2 1 3]);
        try
            fv = isosurface(segVol, 0.5);
            if ~isempty(fv.vertices)
                patchHandle = patch(ax, fv, ...
                    'FaceColor', [0.8 0.8 0.8], ...
                    'EdgeColor', 'none', ...
                    'FaceAlpha', 0.5, ...
                    'HitTest', 'off', ...
                    'PickableParts', 'none');
                surfacePatches(1) = struct( ...
                    'handle', patchHandle, ...
                    'label', 0, ...
                    'vessel', '');
            end
        catch ME
            warning('paramMap_GUI:IsosurfaceFailed', ...
                    'Could not generate isosurface: %s', ME.message);
        end
    end

    branchList = data_struct.branchList(:, 1:3);
    flowVals = data_struct.flowPerHeartCycle_val;

    scatterAll = scatter3(ax, branchList(:,1), branchList(:,2), branchList(:,3), ...
                          16, flowVals, 'filled', ...
                          'MarkerFaceAlpha', 0.8, ...
                          'MarkerEdgeAlpha', 0.8, ...
                          'PickableParts', 'all', ...
                          'HitTest', 'on');
    scatterSel = scatter3(ax, NaN, NaN, NaN, ...
                          40, [1 0 0], 'filled', ...
                          'MarkerEdgeColor', 'k', ...
                          'Visible', 'off', ...
                          'PickableParts', 'all', ...
                          'HitTest', 'on');
end

function locPlots = plotLocMarkers(ax, locInfo)
    if isempty(locInfo)
        locPlots.all = scatter3(ax, NaN, NaN, NaN, 80, 'w', 'filled', ...
                                'HitTest', 'off', 'PickableParts', 'none');
        locPlots.sel = scatter3(ax, NaN, NaN, NaN, 180, 'y', 'filled', ...
                                'MarkerEdgeColor', 'k', ...
                                'HitTest', 'off', 'PickableParts', 'none');
        return;
    end
    coords = vertcat(locInfo.coord);
    locPlots.all = scatter3(ax, coords(:,1), coords(:,2), coords(:,3), ...
                            90, 'w', 'filled', ...
                            'MarkerEdgeColor', [0 0 0], ...
                            'LineWidth', 0.5, ...
                            'HitTest', 'off', ...
                            'PickableParts', 'none');
    locPlots.sel = scatter3(ax, NaN, NaN, NaN, ...
                            220, 'y', 'filled', ...
                            'MarkerEdgeColor', 'k', ...
                            'LineWidth', 1.5, ...
                            'Visible', 'off', ...
                            'HitTest', 'off', ...
                            'PickableParts', 'none');
end

function paramOptions = createParamOptions(data_struct)
    paramOptions = struct('label', {}, 'field', {}, 'units', {}, 'customData', {});
    nPoints = size(data_struct.branchList, 1);
    preferred = {
        'area_val',            'Cross-sectional Area', 'cm^2';
        'diam_val',            'Area Ratio',           '';
        'flowPerHeartCycle_val','Total Flow',          'mL/s';
        'maxVel_val',          'Maximum Velocity',     'cm/s';
        'velMean_val',         'Mean Velocity',        'cm/s';
        'StdvFromMean',        'Flow Consistency',     '';
        'RI_val',              'Resistance Index',     '';
        'PI_val',              'Pulsatility Index',    ''
    };

    added = {};
    for i = 1:size(preferred,1)
        field = preferred{i,1};
        if isfield(data_struct, field) && numel(data_struct.(field)) == nPoints
            paramOptions(end+1) = struct( ...
                'label', preferred{i,2}, ...
                'field', field, ...
                'units', preferred{i,3}, ...
                'customData', []); %#ok<AGROW>
            added{end+1} = field; %#ok<AGROW>
        end
    end

    dataFields = fieldnames(data_struct);
    for i = 1:numel(dataFields)
        field = dataFields{i};
        if ismember(field, added)
            continue;
        end
        vals = data_struct.(field);
        if isnumeric(vals) && isvector(vals) && numel(vals) == nPoints
            label = strrep(field, '_', ' ');
            label = regexprep(label, '(\<[a-z])', '${upper($1)}');
            paramOptions(end+1) = struct( ...
                'label', label, ...
                'field', field, ...
                'units', '', ...
                'customData', []);
            added{end+1} = field; %#ok<AGROW>
        end
    end

    if isfield(data_struct, 'flowPulsatile_val')
        meanFlow = mean(data_struct.flowPulsatile_val, 2, 'omitnan');
        if numel(meanFlow) == nPoints
            paramOptions(end+1) = struct( ...
                'label', 'Mean Flow (Point)', ...
                'field', '', ...
                'units', 'mL/s', ...
                'customData', meanFlow(:));
        end
    end

    if isempty(paramOptions)
        paramOptions = struct('label', 'Total Flow', ...
                              'field', 'flowPerHeartCycle_val', ...
                              'units', 'mL/s', ...
                              'customData', []);
    end
end

function setupCrossAxes(ax, titleText)
    imagesc(ax, zeros(10)); %#ok<MCSUP>
    axis(ax, 'image');
    axis(ax, 'off');
    colormap(ax, gray);
    title(ax, titleText, 'Color', 'w', 'FontSize', 10);
end

function prepareWaveformAxes(ax)
    hold(ax, 'on');
    ax.XColor = [1 1 1];
    ax.YColor = [1 1 1];
    ax.Color = [0.1 0.1 0.1];
end

function applyParameterSelection(fig, idx, resetLimits)
    appData = guidata(fig);
    option = appData.paramOptions(idx);
    if isfield(option, 'customData') && ~isempty(option.customData)
        data = double(option.customData);
    else
        data = double(appData.data_struct.(option.field));
    end
    appData.currentParamIndex = idx;
    appData.paramData = data;
    appData.paramLabel = option.label;
    appData.paramUnits = option.units;
    guidata(fig, appData);

    scatterAll = appData.scatterAll;
    scatterAll.CData = data;

    if strcmpi(appData.paramUnits, '')
        appData.colorbar.Label.String = option.label;
    else
        appData.colorbar.Label.String = sprintf('%s (%s)', option.label, appData.paramUnits);
    end

    finiteVals = data(isfinite(data));
    if isempty(finiteVals)
        finiteVals = [0 1];
    end
    minVal = min(finiteVals);
    maxVal = max(finiteVals);
    if resetLimits || any(~isfinite(caxis(appData.axes)))
        caxis(appData.axes, [minVal maxVal]);
    end
    limits = caxis(appData.axes);
    appData.cbMinEdit.String = sprintf('%.3f', limits(1));
    appData.cbMaxEdit.String = sprintf('%.3f', limits(2));

    if ~isempty(appData.selection.selIndices)
        appData.scatterSel.CData = data(appData.selection.selIndices);
    end

    guidata(fig, appData);
end

function updateSelection(fig, selectionIdx, vesselNames, locKeys)
    appData = guidata(fig);
    scatterAll = appData.scatterAll;
    scatterSel = appData.scatterSel;
    locPlots = appData.locPlots;
    branchList = appData.branchList;
    correspondenceDict = appData.correspondenceDict;
    locInfo = appData.locInfo;

    scatterSel.Visible = 'off';
    locPlots.sel.Visible = 'off';
    appData.selection.key = '';
    appData.selection.locIndex = [];
    appData.selection.selIndices = [];
    appData.selection.pointRow = [];
    appData.cursorMarker.Visible = 'off';
    hidePlaneOverlay(fig);
    updateInfoBox(fig, [], []);

    scatterAll.MarkerFaceAlpha = 0.8;
    scatterAll.MarkerEdgeAlpha = 0.8;
    scatterAll.CData = appData.paramData;

    if selectionIdx <= 1 || isempty(vesselNames)
        scatterAll.Visible = 'on';
        guidata(fig, appData);
        applyMaskAlphas(fig);
        return;
    end

    key = locKeys{selectionIdx-1};
    appData.selection.key = key;

    segments = [];
    if isfield(correspondenceDict, key)
        segments = unique(correspondenceDict.(key));
    elseif strcmpi(key, 'COMM') && isfield(correspondenceDict, 'COMM')
        segments = unique(correspondenceDict.COMM);
    end

    segMask = ismember(branchList(:,4), segments);
    if ~any(segMask)
        warning('paramMap_GUI:EmptySegment', ...
                'No centerline points found for vessel %s.', key);
        guidata(fig, appData);
        hidePlaneOverlay(fig);
        return;
    end

    scatterAll.MarkerFaceAlpha = 0.05;
    scatterAll.MarkerEdgeAlpha = 0.05;

    scatterSel.Visible = 'on';
    scatterSel.XData = branchList(segMask, 1);
    scatterSel.YData = branchList(segMask, 2);
    scatterSel.ZData = branchList(segMask, 3);
    scatterSel.CData = appData.paramData(segMask);

    appData.selection.selIndices = find(segMask);

    locIdx = find(strcmp({locInfo.key}, key), 1);
    if ~isempty(locIdx)
        appData.selection.locIndex = locIdx;
        locEntry = locInfo(locIdx);
        locPlots.sel.Visible = 'on';
        locPlots.sel.XData = locEntry.coord(1);
        locPlots.sel.YData = locEntry.coord(2);
        locPlots.sel.ZData = locEntry.coord(3);
        updateInfoBox(fig, key, locEntry);
        updateSelectedPoint(fig, locEntry.rowIdx);
    else
        updateInfoBox(fig, key, []);
    end

    guidata(fig, appData);
    applyMaskAlphas(fig);
end

function updateInfoBox(fig, key, locEntry)
    appData = guidata(fig);
    infoBox = appData.infoBox;
    if isempty(key)
        infoBox.String = sprintf('Select a vessel to inspect centerline points and LOCs.\nClick any point in the 3D view to inspect its cross-section.');
        return;
    end

    pretty = buildDisplayNames({key});
    label = pretty{1};

    if isempty(locEntry)
        infoBox.String = sprintf('Vessel: %s\nNo LOC data available.', label);
        return;
    end

    paramVal = appData.paramData(locEntry.rowIdx);
    if isempty(appData.paramUnits)
        paramLine = sprintf('%s: %.3f', appData.paramLabel, paramVal);
    else
        paramLine = sprintf('%s: %.3f %s', appData.paramLabel, paramVal, appData.paramUnits);
    end

    infoBox.String = sprintf(['Vessel: %s\n' ...
                              'Segment ID: %d\n' ...
                              'Centerline Index: %d\n' ...
                              'Mean Flow: %.3f mL/s\n' ...
                              'PI: %.3f\n' ...
                              'RI: %.3f\n' ...
                              '%s'], ...
                              label, locEntry.segment, locEntry.clIndex, ...
                              locEntry.flow, locEntry.PI, locEntry.RI, paramLine);
end

function changeParameter(fig, newIndex)
    applyParameterSelection(fig, newIndex, true);
    appData = guidata(fig);
    if ~isempty(appData.selection.selIndices)
        scatterSel = appData.scatterSel;
        scatterSel.CData = appData.paramData(appData.selection.selIndices);
    end
    if ~isempty(appData.selection.locIndex)
        locEntry = appData.locInfo(appData.selection.locIndex);
        updateInfoBox(fig, appData.selection.key, locEntry);
    end
    if ~isempty(appData.selection.pointRow)
        displayPointInfo(fig, appData.selection.pointRow);
    end
    guidata(fig, appData);
end

function changeColormap(fig, idx)
    appData = guidata(fig);
    cmap = appData.colormapList{idx};
    colormap(appData.axes, cmap);
end

function updateColorLimits(fig, whichLimit, value)
    appData = guidata(fig);
    if ~isfinite(value)
        return;
    end
    limits = caxis(appData.axes);
    switch whichLimit
        case 'min'
            limits(1) = value;
        case 'max'
            limits(2) = value;
    end
    if limits(1) >= limits(2)
        limits(2) = limits(1) + eps;
    end
    caxis(appData.axes, limits);
    appData.cbMinEdit.String = sprintf('%.3f', limits(1));
    appData.cbMaxEdit.String = sprintf('%.3f', limits(2));
    guidata(fig, appData);
end

function focusOnSelectedLOC(fig)
    appData = guidata(fig);
    if isempty(appData.selection.key) || isempty(appData.selection.locIndex)
        return;
    end
    locEntry = appData.locInfo(appData.selection.locIndex);
    target = locEntry.coord;
    margin = 10;
    ax = appData.axes;
    xlim(ax, target(1) + margin * [-1 1]);
    ylim(ax, target(2) + margin * [-1 1]);
    zlim(ax, target(3) + margin * [-1 1]);
    camtarget(ax, target);
    updateSelectedPoint(fig, locEntry.rowIdx);
end

function resetView(fig)
    appData = guidata(fig);
    ax = appData.axes;
    axis(ax, 'auto');
    axis(ax, 'equal');
    try
        camlight(ax, 'headlight');
    catch ME
        warning('paramMap_GUI:CamlightReset','camlight failed during reset: %s', ME.message);
    end
    lighting(ax, 'gouraud');
    applyParameterSelection(fig, appData.currentParamIndex, false);
    guidata(fig, appData);
end

function onScatterClick(fig, src, evt)
    selType = get(fig,'SelectionType');
    isShiftSelect = strcmpi(selType, 'extend'); % 'extend' = Shift+click
    if ~strcmp(selType,'normal') && ~isShiftSelect
        return;
    end
    appData = guidata(fig);
    idx = [];

    if ~isempty(evt)
        if isprop(evt,'DataIndex') && ~isempty(evt.DataIndex) && evt.DataIndex > 0
            if src == appData.scatterSel && ~isempty(appData.selection.selIndices)
                idx = appData.selection.selIndices(evt.DataIndex);
            else
                idx = evt.DataIndex;
            end
        elseif isprop(evt,'IntersectionPoint') && ~isempty(evt.IntersectionPoint)
            idx = nearestBranchIndex(appData, evt.IntersectionPoint);
        end
    end

    if isempty(idx)
        pos = get(appData.axes, 'CurrentPoint');
        idx = nearestBranchIndex(appData, pos(1,1:3));
    end

    if ~isempty(idx) && idx > 0
        updateSelectedPoint(fig, idx);
        if isShiftSelect
            syncSelectionToVessel(fig, idx);
        end
    end
end

function updateSelectedPoint(fig, rowIdx)
    appData = guidata(fig);
    if rowIdx < 1 || rowIdx > size(appData.branchList,1)
        return;
    end
    coord = appData.branchList(rowIdx, 1:3);
    appData.cursorMarker.Visible = 'on';
    appData.cursorMarker.XData = coord(1);
    appData.cursorMarker.YData = coord(2);
    appData.cursorMarker.ZData = coord(3);
    appData.selection.pointRow = rowIdx;
    guidata(fig, appData);
    displayPointInfo(fig, rowIdx);
    updateCrossSections(fig, rowIdx);
    updateWaveform(fig, rowIdx);
    updatePlaneOverlay(fig, rowIdx);
end

function displayPointInfo(fig, rowIdx)
    appData = guidata(fig);
    if isempty(rowIdx)
        return;
    end
    paramVal = appData.paramData(rowIdx);
    if strcmpi(appData.paramUnits, '')
        paramLine = sprintf('%s: %.3f', appData.paramLabel, paramVal);
    else
        paramLine = sprintf('%s: %.3f %s', appData.paramLabel, paramVal, appData.paramUnits);
    end
    segID = appData.branchList(rowIdx, 4);
    clIdx = appData.branchList(rowIdx, 5);
    flowVal = appData.flowPerHeartCycle_val(rowIdx);
    piVal = appData.PI_val(rowIdx);
    riVal = appData.RI_val(rowIdx);
    infoBox = appData.infoBox;
    infoBox.String = sprintf(['Selected Point\n' ...
                              'Segment ID: %d\n' ...
                              'Centerline Index: %d\n' ...
                              'Flow: %.3f mL/s\n' ...
                              'PI: %.3f\n' ...
                              'RI: %.3f\n' ...
                              '%s'], ...
                              segID, clIdx, flowVal, piVal, riVal, paramLine);
end

function updateCrossSections(fig, rowIdx)
    appData = guidata(fig);
    imdim = appData.imdim;
    mask = reshape(appData.segmentFull(rowIdx,:), imdim, imdim);
    mag = reshape(appData.MAGcrossection(rowIdx,:), imdim, imdim);
    cd = reshape(appData.timeMIPcrossection(rowIdx,:), imdim, imdim);
    velTA = reshape(appData.vTimeFrameave(rowIdx,:), imdim, imdim);

    v1 = squeeze(appData.VplanesAllx(rowIdx,:,:));
    v2 = squeeze(appData.VplanesAlly(rowIdx,:,:));
    v3 = squeeze(appData.VplanesAllz(rowIdx,:,:));
    VcrossTR = 0.1*(v1 + v2 + v3); % mm/s -> cm/s
    normDim = sqrt(size(VcrossTR,1));
    VcrossTR = reshape(VcrossTR, normDim, normDim, appData.nframes);
    VcrossTR = imresize(VcrossTR(:,:,peakFrameIndex(appData.flowPulsatile(rowIdx,:))), [imdim imdim], 'nearest');

    showCrossSection(appData.axesMAG, mag, mask, 'gray', 'Magnitude');
    showCrossSection(appData.axesCD, cd, mask, 'gray', 'Complex Difference');
    showCrossSection(appData.axesVelTA, velTA, mask, 'gray', 'Velocity (TA)');
    showCrossSection(appData.axesVelTR, VcrossTR, mask, 'gray', 'Velocity (TR)');
end

function idx = peakFrameIndex(flowWaveform)
    [~, idx] = max(abs(flowWaveform));
end

function showCrossSection(ax, imageData, mask, cmapName, titleText)
    axes(ax); %#ok<LAXES>
    cla(ax);
    imagesc(ax, imageData);
    axis(ax, 'image');
    axis(ax, 'off');
    colormap(ax, cmapName);
    hold(ax, 'on');
    contour(ax, mask, [0.5 0.5], 'LineWidth', 0.8, 'LineColor', 'w');
    hold(ax, 'off');
    title(ax, titleText, 'Color', 'w', 'FontSize', 10);
end

function updateWaveform(fig, rowIdx)
    appData = guidata(fig);
    ax = appData.axesWave;
    cla(ax);
    prepareWaveformAxes(ax);
    frames = 0:(appData.nframes-1);
    branchId = appData.branchList(rowIdx,4);
    branchMask = appData.branchList(:,4) == branchId;
    branchIndices = find(branchMask);
    [~, order] = sort(appData.branchList(branchMask,5));
    sortedIdx = branchIndices(order);
    pos = find(sortedIdx == rowIdx);
    neighborRange = max(pos-2,1):min(pos+2, numel(sortedIdx));
    neighborIdxs = sortedIdx(neighborRange);

    colorsPrev = {[0.85 0.3 0.3], [0.6 0 0]};
    colorsNext = {[0.2 0.85 0.2], [0 0.5 0]};
    baseline = [];
    for i = 1:numel(neighborIdxs)
        w = appData.flowPulsatile(neighborIdxs(i),:);
        neighborPos = find(sortedIdx == neighborIdxs(i), 1, 'first');
        offset = neighborPos - pos;
        if neighborIdxs(i) == rowIdx
            baseline = w;
            continue;
        end
        if offset < 0
            clr = colorsPrev{min(abs(offset), numel(colorsPrev))};
        else
            clr = colorsNext{min(offset, numel(colorsNext))};
        end
        plot(ax, frames, w, 'Color', clr, 'LineWidth', 1.1, 'LineStyle', '--');
    end
    if isempty(baseline)
        baseline = appData.flowPulsatile(rowIdx,:);
    end
    plot(ax, frames, baseline, 'Color', [0.1 0.7 1], 'LineWidth', 2.2);
    grid(ax, 'on');
    ax.GridColor = [0.5 0.5 0.5];
    ax.GridAlpha = 0.3;
    xlim(ax, [0 appData.nframes-1]);
    xticks(ax, frames);
    xlabel(ax, 'Cardiac Frame', 'Color', 'w');
    ylabel(ax, 'Flow (mL/s)', 'Color', 'w');
    title(ax, 'Time-Resolved Flow', 'Color', 'w');
end

function updatePlaneOverlay(fig, rowIdx)
    appData = guidata(fig);
    if ~isfield(appData, 'planeLines') || isempty(appData.planeLines) || ...
       ~isfield(appData, 'Planes') || isempty(appData.Planes)
        return;
    end
    if rowIdx < 1 || rowIdx > size(appData.Planes, 1)
        hidePlaneOverlay(fig);
        return;
    end
    planeCoords = squeeze(appData.Planes(rowIdx,:,:));
    if size(planeCoords,1) < 4
        hidePlaneOverlay(fig);
        return;
    end

    centerPt = mean(planeCoords, 1);
    shrinkFactor = 0.7;
    planeCoords = centerPt + shrinkFactor * (planeCoords - centerPt);

    if isfield(appData, 'planePatch') && isgraphics(appData.planePatch)
        set(appData.planePatch, 'Vertices', planeCoords, 'Visible', 'on');
        % Ensure scatter plots and cursor marker are on top for click detection
        if isfield(appData, 'scatterAll') && isgraphics(appData.scatterAll)
            uistack(appData.scatterAll, 'top');
        end
        if isfield(appData, 'scatterSel') && isgraphics(appData.scatterSel)
            uistack(appData.scatterSel, 'top');
        end
        if isfield(appData, 'cursorMarker') && isgraphics(appData.cursorMarker)
            uistack(appData.cursorMarker, 'top');
        end
    end

    edges = [1 2; 2 3; 3 4; 4 1];
    for e = 1:4
        lineHandle = appData.planeLines(e);
        if ~isgraphics(lineHandle)
            continue;
        end
        pts = planeCoords(edges(e,:), :);
        set(lineHandle, ...
            'XData', pts(:,1), ...
            'YData', pts(:,2), ...
            'ZData', pts(:,3), ...
            'Visible', 'on');
    end

    if isfield(appData, 'planeNormal') && isgraphics(appData.planeNormal)
        v1 = planeCoords(2,:) - planeCoords(1,:);
        v2 = planeCoords(4,:) - planeCoords(1,:);
        normalVec = cross(v1, v2);
        nNorm = norm(normalVec);
        if nNorm > 0
            normalVec = normalVec / nNorm;
        end
        edgeVecs = planeCoords([2 3 4 1],:) - planeCoords([1 2 3 4],:);
        edgeLens = vecnorm(edgeVecs, 2, 2);
        planeScale = mean(edgeLens);
        arrowLen = planeScale * 0.45;
        normalVec = normalVec * arrowLen;
        set(appData.planeNormal, ...
            'XData', centerPt(1), ...
            'YData', centerPt(2), ...
            'ZData', centerPt(3), ...
            'UData', normalVec(1), ...
            'VData', normalVec(2), ...
            'WData', normalVec(3), ...
            'Visible', 'on');
        % if isfield(appData, 'planeNormalTip') && isgraphics(appData.planeNormalTip)
        %     tipPoint = centerPt + normalVec;
        % set(appData.planeNormalTip, ...
        %     'XData', tipPoint(1), ...
        %     'YData', tipPoint(2), ...
        %     'ZData', tipPoint(3), ...
        %     'Visible', 'on');
        % end
    end
end

function hidePlaneOverlay(fig)
    appData = guidata(fig);
    if isfield(appData, 'planeLines') && ~isempty(appData.planeLines)
        for e = 1:numel(appData.planeLines)
            lineHandle = appData.planeLines(e);
            if isgraphics(lineHandle)
                set(lineHandle, ...
                    'XData', [NaN NaN], ...
                    'YData', [NaN NaN], ...
                    'ZData', [NaN NaN], ...
                    'Visible', 'off');
            end
        end
    end
    if isfield(appData, 'planePatch') && isgraphics(appData.planePatch)
        set(appData.planePatch, 'Visible', 'off');
    end
    if isfield(appData, 'planeNormal') && isgraphics(appData.planeNormal)
        set(appData.planeNormal, ...
            'XData', NaN, 'YData', NaN, 'ZData', NaN, ...
            'UData', 0, 'VData', 0, 'WData', 0, ...
            'Visible', 'off');
    end
    if isfield(appData, 'planeNormalTip') && isgraphics(appData.planeNormalTip)
        set(appData.planeNormalTip, ...
            'XData', NaN, 'YData', NaN, 'ZData', NaN, ...
            'Visible', 'off');
    end
end

function applyMaskAlphas(fig)
    appData = guidata(fig);
    if ~isfield(appData, 'surfacePatches') || isempty(appData.surfacePatches)
        return;
    end
    if ~isfield(appData, 'alphaSlider') || ~ishandle(appData.alphaSlider)
        return;
    end
    alphaValue = appData.alphaSlider.Value;
    syncOn = isfield(appData, 'syncCheckbox') && ishandle(appData.syncCheckbox) && logical(appData.syncCheckbox.Value);
    selectedKey = '';
    if isfield(appData, 'selection') && isfield(appData.selection, 'key')
        selectedKey = appData.selection.key;
    end
    for i = 1:numel(appData.surfacePatches)
        try
            patchHandle = appData.surfacePatches(i).handle;
            if ~(ishandle(patchHandle) || (isobject(patchHandle) && isvalid(patchHandle)))
                continue;
            end
            targetAlpha = alphaValue;
            if syncOn && ~isempty(selectedKey)
                vesselName = appData.surfacePatches(i).vessel;
                if isempty(vesselName) || ~strcmpi(vesselName, selectedKey)
                    targetAlpha = alphaValue * 0.08;
                end
            end
            patchHandle.FaceAlpha = max(0, min(1, targetAlpha));
        catch
            % Ignore invalid handles
        end
    end
end

function toggleTOFOverlay(fig, enabled)
    appData = guidata(fig);
    if ~isfield(appData, 'tofVolume') || isempty(appData.tofVolume)
        return;
    end
    appData.showTOF = enabled;
    guidata(fig, appData);
    updateTOFOverlay(fig);
end

function updateTOFThreshold(fig, whichLimit, value)
    appData = guidata(fig);
    if ~isfield(appData, 'tofVolume') || isempty(appData.tofVolume) || ~isfinite(value)
        return;
    end
    if isempty(appData.tofThresholds) || numel(appData.tofThresholds) ~= 2
        finiteVals = appData.tofVolume(isfinite(appData.tofVolume));
        if isempty(finiteVals)
            return;
        end
        appData.tofThresholds = [min(finiteVals), max(finiteVals)];
    end
    switch whichLimit
        case 'min'
            appData.tofThresholds(1) = min(value, appData.tofThresholds(2) - eps);
        case 'max'
            appData.tofThresholds(2) = max(value, appData.tofThresholds(1) + eps);
    end
    if isfield(appData, 'tofMinEdit') && isgraphics(appData.tofMinEdit)
        appData.tofMinEdit.String = sprintf('%.2f', appData.tofThresholds(1));
    end
    if isfield(appData, 'tofMaxEdit') && isgraphics(appData.tofMaxEdit)
        appData.tofMaxEdit.String = sprintf('%.2f', appData.tofThresholds(2));
    end
    guidata(fig, appData);
    updateTOFOverlay(fig);
end

function updateTOFOverlay(fig)
    appData = guidata(fig);
    if ~isfield(appData, 'tofVolume') || isempty(appData.tofVolume)
        return;
    end
    enabled = isfield(appData, 'showTOF') && appData.showTOF;
    if ~enabled
        % Close TOF window if it exists
        if isfield(appData, 'tofWindow') && ~isempty(appData.tofWindow) && isgraphics(appData.tofWindow)
            try
                close(appData.tofWindow);
            catch
            end
            appData.tofWindow = [];
            appData.tofVolshow = [];
        end
        guidata(fig, appData);
        return;
    end
    if isempty(appData.tofThresholds)
        finiteVals = appData.tofVolume(isfinite(appData.tofVolume));
        if isempty(finiteVals)
            return;
        end
        % Set default thresholds to min and max of volume intensity
        appData.tofThresholds = [min(finiteVals), max(finiteVals)];
        if isfield(appData, 'tofMinEdit') && isgraphics(appData.tofMinEdit)
            appData.tofMinEdit.String = sprintf('%.2f', appData.tofThresholds(1));
        end
        if isfield(appData, 'tofMaxEdit') && isgraphics(appData.tofMaxEdit)
            appData.tofMaxEdit.String = sprintf('%.2f', appData.tofThresholds(2));
        end
        guidata(fig, appData);
        appData = guidata(fig); % refresh local copy
    end
    % Prepare volume data with thresholding for volshow
    % Note: volshow expects data in original orientation (no permutation needed)
    tofVol = appData.tofVolume;
    thresh = appData.tofThresholds;
    
    % Apply thresholding: values outside range are set to 0 (transparent in volshow)
    % Values within range are kept for volume rendering
    tofVolMasked = tofVol;
    tofVolMasked(tofVol < thresh(1) | tofVol > thresh(2)) = 0;
    
    % Always update the volume, even if thresholded out
    % This ensures the volume comes back when thresholds are adjusted
    
    % Get transparency values
    tofAlpha = 0.15; % default
    if isfield(appData, 'tofAlphaSlider') && isgraphics(appData.tofAlphaSlider)
        tofAlpha = appData.tofAlphaSlider.Value;
    end
    
    % Get mask alpha (for overlaying masks in TOF window)
    maskAlpha = 0.3; % default
    if isfield(appData, 'alphaSlider') && isgraphics(appData.alphaSlider)
        maskAlpha = appData.alphaSlider.Value;
    end
    
    % Use volshow() in a separate window with interactive controls
    try
        % Check if TOF window already exists
        if ~isfield(appData, 'tofWindow') || isempty(appData.tofWindow) || ...
           ~isgraphics(appData.tofWindow)
            % Create new TOF window with volshow and controls
            appData = createTOFWindow(fig, appData, tofVolMasked, tofAlpha, maskAlpha);
        else
            % Update existing TOF window
            appData = updateTOFWindow(fig, appData, tofVolMasked, tofAlpha, maskAlpha);
        end
    catch ME
        warning('paramMap_GUI:TOFVolshowFailed', ...
                'Failed to create/update TOF volume viewer: %s. Make sure volshow is available (Image Processing Toolbox).', ME.message);
        return;
    end
    
    guidata(fig, appData);
end

function toggleAtlasOverlay(fig, enabled)
    appData = guidata(fig);
    if ~isfield(appData, 'atlasVolume') || isempty(appData.atlasVolume)
        return;
    end
    appData.showAtlas = enabled;
    guidata(fig, appData);
    updateAtlasOverlay(fig);
end

function updateAtlasOverlay(fig)
    appData = guidata(fig);
    if ~isfield(appData, 'atlasVolume') || isempty(appData.atlasVolume)
        return;
    end
    enabled = isfield(appData, 'showAtlas') && appData.showAtlas;
    if ~enabled
        if isfield(appData, 'atlasPatches') && ~isempty(appData.atlasPatches)
            for i = 1:numel(appData.atlasPatches)
                h = appData.atlasPatches(i);
                if isgraphics(h)
                    set(h, 'Visible', 'off');
                end
            end
        end
        return;
    end
    segVol = permute(appData.atlasVolume, [2 1 3]);
    labels = unique(segVol(segVol > 0));
    if isempty(labels)
        return;
    end
    % If patches not built or labels changed, rebuild
    needRebuild = isempty(appData.atlasPatches) || ...
                  ~isfield(appData, 'atlasLabels') || ...
                  numel(appData.atlasLabels) ~= numel(labels) || ...
                  any(appData.atlasLabels(:)' ~= labels(:)');
    if needRebuild
        if isfield(appData, 'atlasPatches') && ~isempty(appData.atlasPatches)
            for i = 1:numel(appData.atlasPatches)
                if isgraphics(appData.atlasPatches(i))
                    delete(appData.atlasPatches(i));
                end
            end
        end
        % Get transparency from slider
        atlasAlpha = 0.18; % default
        if isfield(appData, 'atlasAlphaSlider') && isgraphics(appData.atlasAlphaSlider)
            atlasAlpha = appData.atlasAlphaSlider.Value;
        end
        
        colors = lines(numel(labels));
        atlasPatches = gobjects(numel(labels),1);
        for i = 1:numel(labels)
            mask = segVol == labels(i);
            if ~any(mask(:))
                continue;
            end
            try
                fv = isosurface(mask, 0.5);
            catch
                continue;
            end
            if isempty(fv.vertices)
                continue;
            end
            atlasPatches(i) = patch(appData.axes, fv, ...
                'FaceColor', colors(i,:), ...
                'EdgeColor', 'none', ...
                'FaceAlpha', atlasAlpha, ...
                'HitTest', 'off', ...
                'Visible', 'on');
        end
        valid = isgraphics(atlasPatches);
        atlasPatches = atlasPatches(valid);
        appData.atlasPatches = atlasPatches;
        appData.atlasLabels = labels(valid);
        guidata(fig, appData);
    else
        % Update transparency for existing patches
        atlasAlpha = 0.18; % default
        if isfield(appData, 'atlasAlphaSlider') && isgraphics(appData.atlasAlphaSlider)
            atlasAlpha = appData.atlasAlphaSlider.Value;
        end
        
        for i = 1:numel(appData.atlasPatches)
            h = appData.atlasPatches(i);
            if isgraphics(h)
                set(h, 'FaceAlpha', atlasAlpha, 'Visible', 'on');
            end
        end
    end
end

function syncSelectionToVessel(fig, rowIdx)
    appData = guidata(fig);
    if rowIdx < 1 || rowIdx > size(appData.branchList,1)
        return;
    end
    segID = appData.branchList(rowIdx,4);
    vesselKey = findVesselKey(appData.correspondenceDict, segID);
    if isempty(vesselKey)
        return;
    end
    locIdx = find(strcmp(appData.locKeys, vesselKey), 1);
    if isempty(locIdx)
        return;
    end
    newValue = locIdx + 1; % account for "All Vessels"
    vesselNames = appData.vesselNames;
    locKeys = appData.locKeys;
    if appData.dropdown.Value ~= newValue
        appData.dropdown.Value = newValue;
        guidata(fig, appData);
        updateSelection(fig, newValue, vesselNames, locKeys);
    else
        updateSelection(fig, newValue, vesselNames, locKeys);
    end
end

function vesselKey = findVesselKey(correspondenceDict, segID)
    vesselKey = '';
    dictFields = fieldnames(correspondenceDict);
    for i = 1:numel(dictFields)
        key = dictFields{i};
        segments = correspondenceDict.(key);
        if isempty(segments)
            continue;
        end
        if any(segments == segID)
            vesselKey = key;
            return;
        end
    end
end

function idx = nearestBranchIndex(appData, pos)
    coords = appData.branchList(:,1:3);
    dists = sum((coords - pos).^2, 2);
    [minDist, idx] = min(dists);
    if ~isfinite(minDist)
        idx = [];
    end
end

% Function to apply mask alphas to both main window and TOF window
function applyMaskAlphasAndTOF(fig)
    % Apply mask alphas to main window
    applyMaskAlphas(fig);
    
    % Update TOF window if it exists
    appData = guidata(fig);
    if isfield(appData, 'tofWindow') && ~isempty(appData.tofWindow) && isgraphics(appData.tofWindow)
        updateTOFOverlay(fig);
    end
end

% Function to create TOF window with volshow and interactive controls
function appData = createTOFWindow(mainFig, appData, tofVolMasked, tofAlpha, maskAlpha)
    % Create a custom figure with proper layout before volshow
    screenSize = get(0, 'ScreenSize');
    winWidth = round(screenSize(3) * 0.85);
    winHeight = round(screenSize(4) * 0.85);
    winX = round((screenSize(3) - winWidth) / 2);
    winY = round((screenSize(4) - winHeight) / 2);
    
    % Create uifigure (required for volshow 3D rendering)
    tofFig = uifigure('Name', 'TOF Volume Viewer', ...
        'Position', [winX winY winWidth winHeight], ...
        'CloseRequestFcn', @(src,~) closeTOFWindow(mainFig, src), ...
        'Color', [0.94 0.94 0.94]);
    
    % Create main panel for volshow (left side)
    volshowPanel = uipanel('Parent', tofFig, ...
        'Units', 'normalized', ...
        'Position', [0.01 0.01 0.76 0.98], ...
        'BackgroundColor', [0 0 0], ...
        'BorderType', 'none');
    
    % Create control panel (right side)
    controlPanel = uipanel('Parent', tofFig, ...
        'Title', 'TOF Controls', ...
        'Units', 'normalized', ...
        'Position', [0.78 0.01 0.21 0.98], ...
        'BackgroundColor', [0.94 0.94 0.94], ...
        'FontSize', 9);
    
    % Create volshow in the left panel
    try
        volshowObj = volshow(tofVolMasked, ...
            'Parent', volshowPanel, ...
            'Alphamap', linspace(0, tofAlpha, 256), ...
            'Colormap', repmat([1 0.9 0.6], 256, 1), ...
            'RenderingStyle', 'VolumeRendering');
        
        % Get volshow's axes
        volshowAxes = ancestor(volshowObj.Parent, 'axes');
        if isempty(volshowAxes)
            volshowAxes = volshowObj.Parent;
        end
        
        % Store volshow axes reference for overlay
        appData.tofVolshowAxes = volshowAxes;
        
        % Get volume intensity range for sliders
        finiteVals = appData.tofVolume(isfinite(appData.tofVolume));
        volMin = min(finiteVals);
        volMax = max(finiteVals);
        currentMin = appData.tofThresholds(1);
        currentMax = appData.tofThresholds(2);
        
        % TOF Min threshold control
        uicontrol('Style', 'text', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.90 0.90 0.05], ...
            'String', 'TOF Min Threshold', ...
            'BackgroundColor', [0.94 0.94 0.94], ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'left');
        tofMinSlider = uicontrol('Style', 'slider', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.85 0.90 0.04], ...
            'Min', volMin, ...
            'Max', volMax, ...
            'Value', currentMin, ...
            'SliderStep', [0.01 0.1], ...
            'Callback', @(src,~) updateTOFThresholdFromSlider(mainFig, 'min', src.Value));
        tofMinEdit = uicontrol('Style', 'edit', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.80 0.90 0.04], ...
            'String', sprintf('%.2f', currentMin), ...
            'BackgroundColor', [1 1 1], ...
            'FontSize', 9, ...
            'Callback', @(src,~) updateTOFThresholdFromEdit(mainFig, 'min', str2double(src.String)));
        
        % TOF Max threshold control
        uicontrol('Style', 'text', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.75 0.90 0.05], ...
            'String', 'TOF Max Threshold', ...
            'BackgroundColor', [0.94 0.94 0.94], ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'left');
        tofMaxSlider = uicontrol('Style', 'slider', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.70 0.90 0.04], ...
            'Min', volMin, ...
            'Max', volMax, ...
            'Value', currentMax, ...
            'SliderStep', [0.01 0.1], ...
            'Callback', @(src,~) updateTOFThresholdFromSlider(mainFig, 'max', src.Value));
        tofMaxEdit = uicontrol('Style', 'edit', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.65 0.90 0.04], ...
            'String', sprintf('%.2f', currentMax), ...
            'BackgroundColor', [1 1 1], ...
            'FontSize', 9, ...
            'Callback', @(src,~) updateTOFThresholdFromEdit(mainFig, 'max', str2double(src.String)));
        
        % TOF Alpha control
        uicontrol('Style', 'text', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.60 0.90 0.05], ...
            'String', 'TOF Alpha', ...
            'BackgroundColor', [0.94 0.94 0.94], ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'left');
        tofAlphaSliderTOF = uicontrol('Style', 'slider', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.55 0.90 0.04], ...
            'Min', 0, ...
            'Max', 1, ...
            'Value', tofAlpha, ...
            'SliderStep', [0.05 0.1], ...
            'Callback', @(src,~) updateTOFAlphaFromTOFWindow(mainFig, src.Value));
        
        % Mask Alpha control
        uicontrol('Style', 'text', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.50 0.90 0.05], ...
            'String', 'Mask Alpha', ...
            'BackgroundColor', [0.94 0.94 0.94], ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'left');
        maskAlphaSliderTOF = uicontrol('Style', 'slider', ...
            'Parent', controlPanel, ...
            'Units', 'normalized', ...
            'Position', [0.05 0.45 0.90 0.04], ...
            'Min', 0, ...
            'Max', 1, ...
            'Value', maskAlpha, ...
            'SliderStep', [0.05 0.1], ...
            'Callback', @(src,~) updateMaskAlphaFromTOFWindow(mainFig, src.Value));
        
        % Store handles in appData
        appData.tofWindow = tofFig;
        appData.tofVolshow = volshowObj;
        appData.tofMinSlider = tofMinSlider;
        appData.tofMaxSlider = tofMaxSlider;
        appData.tofMinEditTOF = tofMinEdit;
        appData.tofMaxEditTOF = tofMaxEdit;
        appData.tofAlphaSliderTOF = tofAlphaSliderTOF;
        appData.maskAlphaSliderTOF = maskAlphaSliderTOF;
        appData.tofMaskPatches = []; % Store mask overlay patches
        
        % Add mask overlays to TOF window
        appData = addMaskOverlaysToTOF(mainFig, appData, maskAlpha);
        
    catch ME
        if exist('tofFig', 'var') && isgraphics(tofFig)
            close(tofFig);
        end
        rethrow(ME);
    end
end

% Function to add vessel mask overlays to TOF window
function appData = addMaskOverlaysToTOF(mainFig, appData, maskAlpha)
    % Get the segmentation volume
    if ~isfield(appData, 'data_struct') || ~isfield(appData.data_struct, 'segment')
        return;
    end
    
    segVol = appData.data_struct.segment;
    if isempty(segVol)
        return;
    end
    
    try
        % Get the volshow panel (parent of volshow axes)
        volshowPanel = [];
        if isfield(appData, 'tofVolshowAxes') && ~isempty(appData.tofVolshowAxes) && isgraphics(appData.tofVolshowAxes)
            volshowPanel = ancestor(appData.tofVolshowAxes, 'uipanel');
            if isempty(volshowPanel)
                volshowPanel = appData.tofWindow;
            end
        else
            volshowPanel = appData.tofWindow;
        end
        
        % Get volshow axes position
        volshowAxesPos = [0 0 1 1]; % Full panel by default
        if isfield(appData, 'tofVolshowAxes') && ~isempty(appData.tofVolshowAxes) && isgraphics(appData.tofVolshowAxes)
            if isprop(appData.tofVolshowAxes, 'Position')
                volshowAxesPos = appData.tofVolshowAxes.Position;
            end
        end
        
        % Create a separate overlay axes in the volshow panel
        % This allows us to render patches while volshow renders the volume
        overlayAxes = axes('Parent', volshowPanel, ...
            'Units', 'normalized', ...
            'Position', volshowAxesPos, ...
            'Color', 'none', ...
            'Visible', 'on', ...
            'HitTest', 'on', ...  % Make it interactive
            'XLimMode', 'manual', ...
            'YLimMode', 'manual', ...
            'ZLimMode', 'manual', ...
            'XTick', [], ...
            'YTick', [], ...
            'ZTick', [], ...
            'XColor', 'none', ...
            'YColor', 'none', ...
            'ZColor', 'none');
        
        % Make axes interactive - enable rotation and zoom
        rotate3d(overlayAxes, 'on');
        
        % Bring overlay axes to front so patches are visible
        uistack(overlayAxes, 'top');
        
        % Permute segmentation to match coordinate system (same as main window)
        segVolPerm = permute(segVol, [2 1 3]);
        
        % Get unique labels and sort them for consistent coloring
        labels = unique(segVolPerm(segVolPerm > 0));
        labels = sort(labels); % Ensure consistent ordering
        if isempty(labels)
            return;
        end
        
        % Create isosurfaces for each label with distinct colors
        % Use a colormap that provides good distinction
        numLabels = numel(labels);
        if numLabels <= 10
            colors = lines(numLabels);
        elseif numLabels <= 20
            colors = hsv(numLabels);
        else
            % For many labels, use a more varied colormap with better distribution
            colors = hsv(numLabels);
            % Adjust saturation and value for better visibility
            colors(:, 2) = colors(:, 2) * 0.9 + 0.1; % Saturation
            colors(:, 3) = colors(:, 3) * 0.7 + 0.3; % Brightness
        end
        
        maskPatches = gobjects(numLabels, 1);
        patchIdx = 1;
        
        for i = 1:numLabels
            label = labels(i);
            mask = segVolPerm == label;
            if ~any(mask(:))
                continue;
            end
            
            try
                % Downsample mask for performance
                origSize = size(mask);
                downsampleFactor = 2;
                if any(origSize > 100)
                    idx1 = 1:downsampleFactor:origSize(1);
                    idx2 = 1:downsampleFactor:origSize(2);
                    idx3 = 1:downsampleFactor:origSize(3);
                    mask = mask(idx1, idx2, idx3);
                end
                
                fv = isosurface(mask, 0.5);
                if isempty(fv.vertices)
                    continue;
                end
                
                % Scale vertices back if downsampled
                if downsampleFactor > 1
                    fv.vertices = fv.vertices * downsampleFactor;
                end
                
                % Use the color for this specific label index (i, not mod)
                labelColor = colors(i, :);
                
                maskPatches(patchIdx) = patch(overlayAxes, fv, ...
                    'FaceColor', labelColor, ...
                    'EdgeColor', 'none', ...
                    'FaceAlpha', maskAlpha, ...
                    'HitTest', 'off', ...  % Patches don't intercept clicks
                    'PickableParts', 'none', ...
                    'Visible', 'on');
                
                % Store label ID for reference
                maskPatches(patchIdx).UserData = label;
                patchIdx = patchIdx + 1;
            catch ME
                warning('paramMap_GUI:TOFMaskPatchFailed', ...
                        'Failed to create patch for label %d: %s', label, ME.message);
                continue;
            end
        end
        
        % Store only valid patches
        if patchIdx > 1
            validPatches = maskPatches(1:patchIdx-1);
            valid = false(size(validPatches));
            for j = 1:numel(validPatches)
                valid(j) = isgraphics(validPatches(j));
            end
            appData.tofMaskPatches = validPatches(valid);
        else
            appData.tofMaskPatches = gobjects(0);
        end
        appData.tofOverlayAxes = overlayAxes;
        
        % Debug: check if patches were created
        if isempty(appData.tofMaskPatches)
            warning('paramMap_GUI:NoMaskPatches', 'No mask patches were created for TOF overlay');
        end
        
        % Set axes properties to match volume dimensions
        % Use TOF volume size to match volshow's coordinate system
        try
            tofVolSize = size(appData.tofVolume);
            segVolSize = size(segVolPerm);
            
            % volshow uses 1-based indexing, so set limits to match volume dimensions
            % The coordinate system should match: [x, y, z] = [columns, rows, slices]
            set(overlayAxes, ...
                'XLim', [0.5 segVolSize(2)+0.5], ...
                'YLim', [0.5 segVolSize(1)+0.5], ...
                'ZLim', [0.5 segVolSize(3)+0.5]);
            
            axis(overlayAxes, 'equal');
            axis(overlayAxes, 'vis3d');
            
            % Set default view (sagittal-like, matching main window)
            view(overlayAxes, [1 0.1 0.1]);
            
            % Add lighting
            try
                camlight(overlayAxes, 'headlight');
                lighting(overlayAxes, 'gouraud');
            catch
                % Lighting might not work on all axes types
            end
            
            % Bring patches to front so they're visible
            if ~isempty(appData.tofMaskPatches)
                for j = 1:numel(appData.tofMaskPatches)
                    if isgraphics(appData.tofMaskPatches(j))
                        uistack(appData.tofMaskPatches(j), 'top');
                    end
                end
            end
            
            % Ensure axes is on top for interaction and visibility
            uistack(overlayAxes, 'top');
            
            % Force a redraw
            drawnow;
        catch ME
            warning('paramMap_GUI:TOFAxesSetupFailed', ...
                    'Failed to setup overlay axes: %s', ME.message);
        end
        
    catch ME
        warning('paramMap_GUI:TOFMaskOverlayFailed', ...
                'Failed to add mask overlays to TOF window: %s', ME.message);
    end
end

% Function to update TOF window
function appData = updateTOFWindow(mainFig, appData, tofVolMasked, tofAlpha, maskAlpha)
    if isfield(appData, 'tofVolshow') && ~isempty(appData.tofVolshow)
        try
            % Always update volshow data and settings, even if thresholded out
            if isvalid(appData.tofVolshow)
                appData.tofVolshow.VolumeData = tofVolMasked;
                appData.tofVolshow.Alphamap = linspace(0, tofAlpha, 256);
                appData.tofVolshow.Visible = 'on';
                drawnow; % Force update
            end
        catch ME
            warning('paramMap_GUI:TOFUpdateFailed', 'Failed to update TOF volume: %s', ME.message);
        end
    end
    
    % Update control values
    if isfield(appData, 'tofMinSlider') && isgraphics(appData.tofMinSlider)
        appData.tofMinSlider.Value = appData.tofThresholds(1);
    end
    if isfield(appData, 'tofMaxSlider') && isgraphics(appData.tofMaxSlider)
        appData.tofMaxSlider.Value = appData.tofThresholds(2);
    end
    if isfield(appData, 'tofMinEditTOF') && isgraphics(appData.tofMinEditTOF)
        appData.tofMinEditTOF.String = sprintf('%.2f', appData.tofThresholds(1));
    end
    if isfield(appData, 'tofMaxEditTOF') && isgraphics(appData.tofMaxEditTOF)
        appData.tofMaxEditTOF.String = sprintf('%.2f', appData.tofThresholds(2));
    end
    if isfield(appData, 'tofAlphaSliderTOF') && isgraphics(appData.tofAlphaSliderTOF)
        appData.tofAlphaSliderTOF.Value = tofAlpha;
    end
    if isfield(appData, 'maskAlphaSliderTOF') && isgraphics(appData.maskAlphaSliderTOF)
        appData.maskAlphaSliderTOF.Value = maskAlpha;
    end
    
    % Create mask overlays if they don't exist
    if ~isfield(appData, 'tofMaskPatches') || isempty(appData.tofMaskPatches)
        appData = addMaskOverlaysToTOF(mainFig, appData, maskAlpha);
    else
        % Update mask overlay alpha
        for i = 1:numel(appData.tofMaskPatches)
            if isgraphics(appData.tofMaskPatches(i))
                try
                    appData.tofMaskPatches(i).FaceAlpha = maskAlpha;
                catch
                end
            end
        end
    end
end

% Callback functions for TOF window controls
function updateTOFThresholdFromSlider(mainFig, whichLimit, value)
    appData = guidata(mainFig);
    updateTOFThreshold(mainFig, whichLimit, value);
    appData = guidata(mainFig); % Refresh after update
    % Update edit box in TOF window
    if strcmp(whichLimit, 'min') && isfield(appData, 'tofMinEditTOF') && isgraphics(appData.tofMinEditTOF)
        appData.tofMinEditTOF.String = sprintf('%.2f', value);
    elseif strcmp(whichLimit, 'max') && isfield(appData, 'tofMaxEditTOF') && isgraphics(appData.tofMaxEditTOF)
        appData.tofMaxEditTOF.String = sprintf('%.2f', value);
    end
    guidata(mainFig, appData);
end

function updateTOFThresholdFromEdit(mainFig, whichLimit, value)
    if ~isfinite(value)
        return;
    end
    updateTOFThreshold(mainFig, whichLimit, value);
    % Update slider in TOF window
    appData = guidata(mainFig);
    if strcmp(whichLimit, 'min') && isfield(appData, 'tofMinSlider') && isgraphics(appData.tofMinSlider)
        appData.tofMinSlider.Value = value;
    elseif strcmp(whichLimit, 'max') && isfield(appData, 'tofMaxSlider') && isgraphics(appData.tofMaxSlider)
        appData.tofMaxSlider.Value = value;
    end
end

function updateTOFAlphaFromTOFWindow(mainFig, value)
    appData = guidata(mainFig);
    if isfield(appData, 'tofAlphaSlider') && isgraphics(appData.tofAlphaSlider)
        appData.tofAlphaSlider.Value = value;
    end
    guidata(mainFig, appData);
    % Update TOF overlay with new alpha
    updateTOFOverlay(mainFig);
end

function updateMaskAlphaFromTOFWindow(mainFig, value)
    appData = guidata(mainFig);
    if isfield(appData, 'alphaSlider') && isgraphics(appData.alphaSlider)
        appData.alphaSlider.Value = value;
    end
    guidata(mainFig, appData);
    applyMaskAlphasAndTOF(mainFig);
end

function closeTOFWindow(mainFig, tofFig)
    appData = guidata(mainFig);
    if isfield(appData, 'tofVolshow') && ~isempty(appData.tofVolshow)
        try
            delete(appData.tofVolshow);
        catch
        end
        appData.tofVolshow = [];
    end
    appData.tofWindow = [];
    if isfield(appData, 'showTOF')
        appData.showTOF = false;
    end
    if isfield(appData, 'tofCheckbox') && isgraphics(appData.tofCheckbox)
        appData.tofCheckbox.Value = 0;
    end
    guidata(mainFig, appData);
    delete(tofFig);
end

% Helper function to create volume rendering in the same axes
function patches = createVolumeRendering(ax, volume, alpha, color, affineMat)
    % Create volume rendering using multiple isosurfaces at different thresholds
    % This simulates volshow's volume rendering but works in regular axes
    
    patches = {};
    
    % Get volume dimensions
    volSize = size(volume);
    
    % Create coordinate grids
    % Transform voxel coordinates to world coordinates using affine matrix
    [x, y, z] = meshgrid(1:volSize(2), 1:volSize(1), 1:volSize(3));
    
    % Apply affine transformation to get world coordinates
    if ~isempty(affineMat) && size(affineMat, 1) == 4 && size(affineMat, 2) == 4
        % Convert voxel coordinates to homogeneous coordinates
        coords = [x(:), y(:), z(:), ones(numel(x), 1)]';
        % Transform to world coordinates
        worldCoords = affineMat * coords;
        % Reshape back to volume dimensions
        x = reshape(worldCoords(1, :), volSize);
        y = reshape(worldCoords(2, :), volSize);
        z = reshape(worldCoords(3, :), volSize);
    end
    
    % Find non-zero values for rendering
    validMask = volume > 0;
    if ~any(validMask(:))
        return;
    end
    
    % Get intensity range for thresholding
    validVals = volume(validMask);
    minVal = min(validVals);
    maxVal = max(validVals);
    
    % Create multiple isosurfaces at different thresholds for volume rendering effect
    % Use fewer isosurfaces for performance, but enough for smooth appearance
    numIsosurfaces = 8;
    thresholds = linspace(minVal + 0.1*(maxVal-minVal), maxVal, numIsosurfaces);
    
    % Calculate alpha for each isosurface (higher intensity = more opaque)
    alphas = linspace(alpha * 0.3, alpha, numIsosurfaces);
    
    for i = 1:numIsosurfaces
        try
            % Create isosurface at this threshold
            fv = isosurface(x, y, z, volume, thresholds(i));
            
            if ~isempty(fv.vertices)
                % Create patch with appropriate transparency
                p = patch(ax, fv, ...
                    'FaceColor', color, ...
                    'EdgeColor', 'none', ...
                    'FaceAlpha', alphas(i), ...
                    'HitTest', 'off', ...
                    'Visible', 'on');
                patches{end+1} = p;
            end
        catch
            % Skip if isosurface creation fails
            continue;
        end
    end
    
    % If no isosurfaces were created, create a single one at median threshold
    if isempty(patches)
        try
            fv = isosurface(x, y, z, volume, median(validVals));
            if ~isempty(fv.vertices)
                p = patch(ax, fv, ...
                    'FaceColor', color, ...
                    'EdgeColor', 'none', ...
                    'FaceAlpha', alpha, ...
                    'HitTest', 'off', ...
                    'Visible', 'on');
                patches{1} = p;
            end
        catch
        end
    end
end

% Helper function to update existing volume rendering
function updateVolumeRendering(patches, volume, alpha, affineMat)
    % Update existing volume rendering patches with new data
    
    if isempty(patches)
        return;
    end
    
    % Get volume dimensions
    volSize = size(volume);
    
    % Create coordinate grids
    [x, y, z] = meshgrid(1:volSize(2), 1:volSize(1), 1:volSize(3));
    
    % Apply affine transformation
    if ~isempty(affineMat) && size(affineMat, 1) == 4 && size(affineMat, 2) == 4
        coords = [x(:), y(:), z(:), ones(numel(x), 1)]';
        worldCoords = affineMat * coords;
        x = reshape(worldCoords(1, :), volSize);
        y = reshape(worldCoords(2, :), volSize);
        z = reshape(worldCoords(3, :), volSize);
    end
    
    % Find valid values
    validMask = volume > 0;
    if ~any(validMask(:))
        % Hide all patches if no data
        for i = 1:length(patches)
            if isgraphics(patches{i}) && isvalid(patches{i})
                patches{i}.Visible = 'off';
            end
        end
        return;
    end
    
    validVals = volume(validMask);
    minVal = min(validVals);
    maxVal = max(validVals);
    
    % Update patches
    numIsosurfaces = min(length(patches), 8);
    thresholds = linspace(minVal + 0.1*(maxVal-minVal), maxVal, numIsosurfaces);
    alphas = linspace(alpha * 0.3, alpha, numIsosurfaces);
    
    for i = 1:numIsosurfaces
        if i <= length(patches) && isgraphics(patches{i}) && isvalid(patches{i})
            try
                % Create new isosurface
                fv = isosurface(x, y, z, volume, thresholds(i));
                if ~isempty(fv.vertices)
                    % Update patch
                    set(patches{i}, ...
                        'Vertices', fv.vertices, ...
                        'Faces', fv.faces, ...
                        'FaceAlpha', alphas(i), ...
                        'Visible', 'on');
                else
                    patches{i}.Visible = 'off';
                end
            catch
                patches{i}.Visible = 'off';
            end
        end
    end
    
    % Hide extra patches if we have fewer thresholds now
    for i = numIsosurfaces + 1:length(patches)
        if isgraphics(patches{i}) && isvalid(patches{i})
            patches{i}.Visible = 'off';
        end
    end
end

