function paramMap_GUI()
% paramMap_GUI - Interactive viewer for automated QVT+ outputs.
%
% This tool lets you inspect the results generated by paramMap_auto.m.
% It loads the processed QVT data, reconstructed eICAB correspondence, and
% automatically selected LOCs, then launches a lightweight GUI to explore
% the vasculature, isolate vessels, and visualize LOC positions.
%
% Usage:
%   >> paramMap_GUI
%
% The script will prompt you to select the output directory created by
% paramMap_auto (the folder containing qvtData_ISOfix_*.mat, SummaryParamTool.xls,
% multilabel_QVTseg.nii, etc.).

    outputDir = uigetdir(pwd, 'Select a QVT+ output directory');
    if isequal(outputDir, 0)
        disp('paramMap_GUI: No folder selected. Exiting.');
        return;
    end
    matInfo = dir(fullfile(outputDir, 'qvtData_ISOfix_*.mat'));
    if isempty(matInfo)
        error('paramMap_GUI:MissingData', ...
              'No qvtData_ISOfix_*.mat file found in %s.', outputDir);
    end

    % In case there are multiple processed files, pick the most recent
    [~, newestIdx] = max([matInfo.datenum]);
    matFile = fullfile(outputDir, matInfo(newestIdx).name);

    dataVars = load(matFile, 'data_struct', 'Vel_Time_Res');
    data_struct = dataVars.data_struct;
    Vel_Time_Res = dataVars.Vel_Time_Res;

    % Rebuild correspondence dictionary and LOCs from outputs on disk
    try
        [correspondenceDict, multiQVT] = generateCorrespondenceDict(outputDir, data_struct);
    catch ME
        error('paramMap_GUI:LabelFilesMissing', ...
              'Unable to rebuild correspondence dictionary: %s', ME.message);
    end

    [correspondenceDict, LOCs] = generateLOCs(data_struct, correspondenceDict, multiQVT);

    % Filter LOCs that do not have the expected [segment, idx] structure
    locKeys = fieldnames(LOCs);
    validLocMask = false(size(locKeys));
    for iKey = 1:numel(locKeys)
        entry = LOCs.(locKeys{iKey});
        validLocMask(iKey) = isnumeric(entry) && isvector(entry) && numel(entry) == 2;
    end
    locKeys = locKeys(validLocMask);

    if isempty(locKeys)
        warning('paramMap_GUI:NoLOCs', 'No LOC entries detected.');
    end

    locInfo = computeLocInfo(locKeys, LOCs, data_struct);

    vesselNames = buildDisplayNames(locKeys);
    paramOptions = createParamOptions(data_struct);
    cmapList = {'parula','turbo','jet','hot','cool','summer','autumn','winter','gray','bone'};

    app.figure = figure('Name', 'QVT+ Viewer', ...
                        'NumberTitle', 'off', ...
                        'Color', [1.0 1.0 1.0], ...
                        'Units', 'normalized', ...
                        'Position', [0.08 0.08 0.84 0.82]);
    movegui(app.figure, 'center');

    % Render window on the left
    app.axes = axes('Parent', app.figure, ...
                    'Position', [0.02 0.02 0.58 0.96], ...
                    'Color', [1.0 1.0 1.0]);
    hold(app.axes, 'on');
    axis(app.axes, 'equal');
    axis(app.axes, 'off');
    view(app.axes, 3);
    % rotate3d(app.figure, 'on');

    % Try to load multilabel volume for colored isosurfaces
    multilabelPath = fullfile(outputDir, 'multilabel_QVTseg.nii');
    if exist(multilabelPath, 'file')
        try
            V = spm_vol(multilabelPath);
            multiQVTvol = spm_read_vols(V);
        catch
            multiQVTvol = [];
        end
    else
        multiQVTvol = [];
    end

    % Prefer whole-brain atlas; fallback to CW if WB not available
    atlasVolume = [];
    atlasPathWB = fullfile(outputDir, 'r_TOF_eICAB_WB.nii');
    atlasPathCW = fullfile(outputDir, 'r_TOF_eICAB_CW.nii');

    if exist(atlasPathWB, 'file')
        try
            atlasHeader = spm_vol(atlasPathWB);
            atlasVolume = spm_read_vols(atlasHeader);
        catch ME
            warning('paramMap_GUI:LoadAtlas','Failed to load r_TOF_eICAB_WB.nii: %s', ME.message);
            atlasVolume = [];
        end
    elseif exist(atlasPathCW, 'file')
        try
            atlasHeader = spm_vol(atlasPathCW);
            atlasVolume = spm_read_vols(atlasHeader);
        catch ME
            warning('paramMap_GUI:LoadAtlas','Failed to load r_TOF_eICAB_CW.nii: %s', ME.message);
            atlasVolume = [];
        end
    end

    [surfacePatches, scatterAll, scatterSel] = plotCenterlines(app.axes, data_struct, correspondenceDict, multiQVTvol);
    locPlots = plotLocMarkers(app.axes, locInfo);
    cursorMarker = scatter3(app.axes, NaN, NaN, NaN, ...
                            160, [0 1 0], 'filled', ...
                            'MarkerEdgeColor', 'k', ...
                            'Visible', 'off', ...
                            'HitTest', 'off', ...
                            'PickableParts', 'none');
    planeLines = gobjects(4,1);
    for iLine = 1:4
        planeLines(iLine) = plot3(app.axes, NaN, NaN, NaN, ...
                                  'Color', [1 0.25 0.25], ...
                                  'LineWidth', 1.6, ...
                                  'HitTest', 'off', ...
                                  'PickableParts', 'none', ...
                                  'Visible', 'off');
    end
    planePatch = patch(app.axes, ...
                       'Faces', [1 2 3 4], ...
                       'Vertices', zeros(4,3), ...
                       'FaceColor', [1 0.2 0.2], ...
                       'FaceAlpha', 0.5, ...
                       'EdgeColor', 'none', ...
                       'Visible', 'off', ...
                       'HitTest', 'off', ...
                       'PickableParts', 'none');
    planeNormal = quiver3(app.axes, NaN, NaN, NaN, 0, 0, 0, ...
                          'Color', [1 0.45 0.2], ...
                          'LineWidth', 2.0, ...
                          'AutoScale', 'off', ...
                          'HitTest', 'off', ...
                          'Visible', 'off');
    planeNormalTip = scatter3(app.axes, NaN, NaN, NaN, ...
                              40, [1 0.25 0.25], 'filled', ...
                              'MarkerEdgeColor', 'k', ...
                              'Visible', 'off', ...
                              'HitTest', 'off', ...
                              'PickableParts', 'none');

    colormap(app.axes, parula);

    % Right Panel Controls
    % Group 1: Vessel and Parameter selection (Top)
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.66 0.95 0.15 0.022], ...
              'String', 'Vessel', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    dropdownList = [{'All Vessels'}, vesselNames(:)'];
    dropdown = uicontrol('Style', 'popupmenu', ...
                         'Parent', app.figure, ...
                         'Units', 'normalized', ...
                         'Position', [0.66 0.92 0.15 0.028], ...
                         'String', dropdownList, ...
                         'BackgroundColor', [1 1 1], ...
                         'ForegroundColor', [0 0 0], ...
                         'FontSize', 8);

    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.82 0.95 0.14 0.022], ...
              'String', 'Parameter', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    paramDropdown = uicontrol('Style', 'popupmenu', ...
                              'Parent', app.figure, ...
                              'Units', 'normalized', ...
                              'Position', [0.82 0.92 0.14 0.028], ...
                              'String', {paramOptions.label}, ...
                              'BackgroundColor', [1 1 1], ...
                              'ForegroundColor', [0 0 0], ...
                              'FontSize', 8);
    paramDropdown.Value = 1;

    % Group 2: Colormap and Colorbar limits
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.66 0.89 0.08 0.022], ...
              'String', 'Colormap', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    cmapDropdown = uicontrol('Style', 'popupmenu', ...
                             'Parent', app.figure, ...
                             'Units', 'normalized', ...
                             'Position', [0.66 0.86 0.08 0.028], ...
                             'String', cmapList, ...
                             'BackgroundColor', [1 1 1], ...
                             'ForegroundColor', [0 0 0], ...
                             'FontSize', 8);
    cmapDropdown.Value = 1;

    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.75 0.89 0.05 0.022], ...
              'String', 'Min', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    cbMinEdit = uicontrol('Style', 'edit', ...
                          'Parent', app.figure, ...
                          'Units', 'normalized', ...
                          'Position', [0.75 0.86 0.05 0.028], ...
                          'BackgroundColor', [1 1 1], ...
                          'ForegroundColor', [0 0 0], ...
                          'FontSize', 8);

    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.81 0.89 0.05 0.022], ...
              'String', 'Max', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    cbMaxEdit = uicontrol('Style', 'edit', ...
                          'Parent', app.figure, ...
                          'Units', 'normalized', ...
                          'Position', [0.81 0.86 0.05 0.028], ...
                          'BackgroundColor', [1 1 1], ...
                          'ForegroundColor', [0 0 0], ...
                          'FontSize', 8);

    % Group 3: Mask Transparency & Sync
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.66 0.83 0.09 0.022], ...
              'String', 'Mask Alpha', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    alphaSlider = uicontrol('Style', 'slider', ...
                            'Parent', app.figure, ...
                            'Units', 'normalized', ...
                            'Position', [0.66 0.80 0.09 0.028], ...
                            'Min', 0, ...
                            'Max', 1, ...
                            'Value', 0.3, ...
                            'SliderStep', [0.05 0.1]);

    syncCheckbox = uicontrol('Style', 'checkbox', ...
                             'Parent', app.figure, ...
                             'Units', 'normalized', ...
                             'Position', [0.77 0.80 0.10 0.028], ...
                             'String', 'Sync Masks', ...
                             'Value', 1, ...
                             'ForegroundColor', [0 0 0], ...
                             'BackgroundColor', [1 1 1], ...
                             'FontSize', 8, ...
                             'HorizontalAlignment', 'left');

    % Group 4: Atlas Overlay (Reorganized)
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.66 0.77 0.09 0.022], ...
              'String', 'Atlas Alpha', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    atlasAlphaSlider = uicontrol('Style', 'slider', ...
                                 'Parent', app.figure, ...
                                 'Units', 'normalized', ...
                                 'Position', [0.66 0.74 0.09 0.028], ...
                                 'Min', 0, ...
                                 'Max', 1, ...
                                 'Value', 0.18, ...
                                 'SliderStep', [0.05 0.1]);

    atlasCheckbox = uicontrol('Style', 'checkbox', ...
                              'Parent', app.figure, ...
                              'Units', 'normalized', ...
                              'Position', [0.77 0.74 0.10 0.028], ...
                              'String', 'Show Atlas', ...
                              'Value', 0, ...
                              'ForegroundColor', [0 0 0], ...
                              'BackgroundColor', [1 1 1], ...
                              'FontSize', 8, ...
                              'HorizontalAlignment', 'left');

    % Group 5: Action Buttons
    focusButton = uicontrol('Style', 'pushbutton', ...
                            'Parent', app.figure, ...
                            'Units', 'normalized', ...
                            'Position', [0.66 0.68 0.10 0.028], ...
                            'String', 'Focus LOC', ...
                            'FontSize', 8);

    resetButton = uicontrol('Style', 'pushbutton', ...
                            'Parent', app.figure, ...
                            'Units', 'normalized', ...
                            'Position', [0.77 0.68 0.10 0.028], ...
                            'String', 'Reset', ...
                            'FontSize', 8, ...
                            'Callback', @(~,~) resetView(app.figure));

    % Vector Settings (Thickness & Scale) - Moved ABOVE Checkbox position
    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.88 0.85 0.10 0.022], ...
              'String', 'Vec Scale', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    vecScaleEdit = uicontrol('Style', 'edit', ...
                             'Parent', app.figure, ...
                             'Units', 'normalized', ...
                             'Position', [0.88 0.825 0.10 0.028], ...
                             'String', '2.5', ...
                             'BackgroundColor', [1 1 1], ...
                             'ForegroundColor', [0 0 0], ...
                             'FontSize', 8, ...
                             'Callback', @(~,~) updateVectors(app.figure));

    uicontrol('Style', 'text', ...
              'Parent', app.figure, ...
              'Units', 'normalized', ...
              'Position', [0.88 0.795 0.10 0.022], ...
              'String', 'Vec Thick', ...
              'BackgroundColor', [1 1 1], ...
              'ForegroundColor', [0 0 0], ...
              'FontSize', 8, ...
              'HorizontalAlignment', 'left');
    vecThickEdit = uicontrol('Style', 'edit', ...
                             'Parent', app.figure, ...
                             'Units', 'normalized', ...
                             'Position', [0.88 0.77 0.10 0.028], ...
                             'String', '3.0', ...
                             'BackgroundColor', [1 1 1], ...
                             'ForegroundColor', [0 0 0], ...
                             'FontSize', 8, ...
                             'Callback', @(~,~) updateVectors(app.figure));

    % Vector Field Toggle - Moved slightly UP
    vectorCheckbox = uicontrol('Style', 'checkbox', ...
                        'Parent', app.figure, ...
                        'Units', 'normalized', ...
                               'Position', [0.88 0.73 0.10 0.028], ...
                               'String', 'Vectors', ...
                               'Value', 0, ...
                               'BackgroundColor', [1 1 1], ...
                               'ForegroundColor', [0 0 0], ...
                               'FontSize', 8, ...
                               'Callback', @(src,~) toggleVectors(app.figure, src.Value));

    % Images displayed in a row (1x4)
    app.axesMAG = axes('Parent', app.figure, ...
                       'Position', [0.65 0.52 0.08 0.12], ...
                       'Color', 'w', ...
                       'HandleVisibility', 'callback', ...
                       'HitTest', 'off');
    app.axesCD = axes('Parent', app.figure, ...
                      'Position', [0.735 0.52 0.08 0.12], ...
                      'Color', 'w', ...
                      'HandleVisibility', 'callback', ...
                      'HitTest', 'off');
    app.axesVelTA = axes('Parent', app.figure, ...
                         'Position', [0.82 0.52 0.08 0.12], ...
                         'Color', 'w', ...
                         'HandleVisibility', 'callback', ...
                         'HitTest', 'off');
    app.axesVelTR = axes('Parent', app.figure, ...
                         'Position', [0.905 0.52 0.08 0.12], ...
                         'Color', 'w', ...
                         'HandleVisibility', 'callback', ...
                         'HitTest', 'off');

    % Flow Chart below images
    app.axesWave = axes('Parent', app.figure, ...
                        'Position', [0.65 0.28 0.34 0.20], ...
                        'Color', [1 1 1], ...
                        'HandleVisibility', 'callback', ...
                        'HitTest', 'off');

    % Animation Controls (Below Flow Chart) - Lowered position
    playButton = uicontrol('Style', 'pushbutton', ...
                           'Parent', app.figure, ...
                           'Units', 'normalized', ...
                           'Position', [0.66 0.18 0.05 0.025], ...
                           'String', 'Play', ...
                           'FontSize', 8, ...
                           'Callback', @(src,~) toggleAnimation(app.figure, src));
    
    timeSlider = uicontrol('Style', 'slider', ...
                           'Parent', app.figure, ...
                           'Units', 'normalized', ...
                           'Position', [0.72 0.18 0.26 0.025], ...
                           'Min', 1, 'Max', data_struct.nframes, ...
                           'Value', 1, ...
                           'SliderStep', [1/(data_struct.nframes-1), 1/(data_struct.nframes-1)], ...
                           'Callback', @(src,~) updateTimeFrame(app.figure, round(src.Value)));

    % Info Box - Moved to Bottom-Left over render window
    infoBox = uicontrol('Style', 'text', ...
                        'Parent', app.figure, ...
                        'Units', 'normalized', ...
                        'Position', [0.02 0.02 0.12 0.14], ...
                        'String', '', ...
                        'HorizontalAlignment', 'left', ...
                        'BackgroundColor', [1 1 1 0], ... % Force White Background
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', 9);
                        
    % Attempt to make Info Box transparent (MATLAB R2014b+ limitation)
    % User reported "completely black" with 'none'. 
    % Reverting to White [1 1 1] to ensure visibility.
    % To fake transparency, we would need to capture the axes background, 
    % but simply White is safer and readable.
    set(infoBox, 'BackgroundColor', [1 1 1]); 
    
    % 1x3 View Panel (Bottom Right)
    app.axesCor = axes('Parent', app.figure, ...
                       'Position', [0.65 0.02 0.10 0.14], ...
                       'Color', 'w', ...
                       'HandleVisibility', 'callback', ...
                       'HitTest', 'off');
    app.axesAx = axes('Parent', app.figure, ...
                      'Position', [0.76 0.02 0.10 0.14], ...
                      'Color', 'w', ...
                      'HandleVisibility', 'callback', ...
                      'HitTest', 'off');
    app.axesZoom = axes('Parent', app.figure, ...
                        'Position', [0.87 0.02 0.10 0.14], ...
                        'Color', 'w', ...
                        'HandleVisibility', 'callback', ...
                        'HitTest', 'off');

    setupCrossAxes(app.axesCor, 'Coronal');
    setupCrossAxes(app.axesAx, 'Axial');
    setupCrossAxes(app.axesZoom, '3D Zoom');

    setupCrossAxes(app.axesMAG, 'MAG');
    setupCrossAxes(app.axesCD, 'CD');
    setupCrossAxes(app.axesVelTA, 'Velocity (TA)');
    setupCrossAxes(app.axesVelTR, 'Velocity (TR)');
    prepareWaveformAxes(app.axesWave);

    try
        camlight(app.axes, 'headlight');
    catch ME
        warning('paramMap_GUI:CamlightInit','camlight failed: %s', ME.message);
    end
    lighting(app.axes, 'flat'); % Flat lighting to reduce smoothing appearance
    
    % Set initial camera zoom (Zoom in slightly)
    camzoom(app.axes, 1.2);

    cb = colorbar(app.axes);
    cb.Color = [0 0 0];
    cb.Label.Color = [0 0 0];

    appData.branchList = data_struct.branchList;
    appData.area_val = data_struct.area_val;
    appData.diam_val = data_struct.diam_val;
    appData.flowPerHeartCycle_val = data_struct.flowPerHeartCycle_val;
    appData.maxVel_val = data_struct.maxVel_val;
    appData.velMean_val = data_struct.velMean_val;
    appData.StdvFromMean = data_struct.StdvFromMean;
    appData.PI_val = data_struct.PI_val;
    appData.RI_val = data_struct.RI_val;
    appData.locInfo = locInfo;
    appData.correspondenceDict = correspondenceDict;
    appData.locPlots = locPlots;
    appData.scatterAll = scatterAll;
    appData.scatterSel = scatterSel;
    appData.cursorMarker = cursorMarker;
    appData.planeLines = planeLines;
    appData.planePatch = planePatch;
    appData.planeNormal = planeNormal;
    appData.planeNormalTip = planeNormalTip;
    appData.infoBox = infoBox;
    appData.axes = app.axes;
    appData.axesMAG = app.axesMAG;
    appData.axesCD = app.axesCD;
    appData.axesVelTA = app.axesVelTA;
    appData.axesVelTR = app.axesVelTR;
    appData.axesWave = app.axesWave;
    appData.selection = struct('key', '', 'locIndex', [], 'pointRow', [], 'selIndices', []);
    appData.paramOptions = paramOptions;
    appData.surfacePatches = surfacePatches;
    appData.alphaSlider = alphaSlider;
    appData.syncCheckbox = syncCheckbox;
    appData.atlasCheckbox = atlasCheckbox;
    appData.atlasAlphaSlider = atlasAlphaSlider;
    appData.colormapList = cmapList;
    appData.paramDropdown = paramDropdown;
    appData.cmapDropdown = cmapDropdown;
    appData.cbMinEdit = cbMinEdit;
    appData.cbMaxEdit = cbMaxEdit;
    appData.colorbar = cb;
    appData.dropdown = dropdown;
    appData.locKeys = locKeys;
    appData.vesselNames = vesselNames;
    appData.flowPulsatile = data_struct.flowPulsatile_val;
    appData.nframes = data_struct.nframes;
    appData.timeres = data_struct.timeres;
    appData.segmentFull = data_struct.segmentFull;
    appData.Planes = data_struct.Planes;
    appData.MAGcrossection = data_struct.MAGcrossection;
    appData.timeMIPcrossection = data_struct.timeMIPcrossection;
    appData.vTimeFrameave = data_struct.vTimeFrameave;
    appData.VplanesAllx = Vel_Time_Res.VplanesAllx;
    appData.VplanesAlly = Vel_Time_Res.VplanesAlly;
    appData.VplanesAllz = Vel_Time_Res.VplanesAllz;
    appData.imdim = sqrt(size(data_struct.segmentFull, 2));
    appData.data_struct = data_struct;
    appData.currentParamIndex = 1;
    appData.atlasVolume = atlasVolume;
    appData.atlasPatches = [];
    appData.atlasLabels = [];
    appData.showAtlas = false;
    
    % Store handles
    appData.vectorCheckbox = vectorCheckbox;
    appData.vecThickEdit = vecThickEdit;
    appData.vecScaleEdit = vecScaleEdit;
    appData.playButton = playButton;
    appData.timeSlider = timeSlider;
    appData.axesCor = app.axesCor;
    appData.axesAx = app.axesAx;
    appData.axesZoom = app.axesZoom;

    % Compute tangents for vector field
    % Q: How is exactly the directions of the vectors being computed?
    % A: Vectors are computed as the gradient of the vessel centerline coordinates.
    %    The centerline is an ordered list of points (x,y,z).
    %    The gradient vector at point i is derived from (P(i+1) - P(i-1)), representing
    %    the tangent direction along the vessel path.
    coords = data_struct.branchList(:, 1:3);
    tangents = zeros(size(coords));
    bIDs = unique(data_struct.branchList(:,4));
    for i = 1:numel(bIDs)
        mask = data_struct.branchList(:,4) == bIDs(i);
        pts = coords(mask, :);
        if size(pts,1) > 1
            % Gradient along the path
            t = gradient(pts')';
            % Normalize
            lens = sqrt(sum(t.^2, 2));
            t = t ./ (lens + eps);
            % Original direction (Brain arteries usually flow Up/Distal)
            tangents(mask, :) = t;
        end
    end
    appData.tangents = tangents;
    appData.currentFrame = 1;
    appData.isAnimating = false;
    appData.timer = [];
    
    % Compute global flow range for consistent animation coloring (Absolute Magnitude)
    allFlow = data_struct.flowPulsatile_val;
    absFlow = abs(allFlow);
    appData.globalFlowRange = [min(absFlow(:), [], 'omitnan'), max(absFlow(:), [], 'omitnan')];
    if appData.globalFlowRange(1) >= appData.globalFlowRange(2)
        appData.globalFlowRange(2) = appData.globalFlowRange(1) + 1;
    end
    
    % Removed Velocity pre-computation as requested to stick to Flow

    guidata(app.figure, appData);

    dropdown.Callback = @(src, ~) updateSelection(app.figure, src.Value, vesselNames, locKeys);
    paramDropdown.Callback = @(src, ~) changeParameter(app.figure, src.Value);
    cmapDropdown.Callback = @(src, ~) changeColormap(app.figure, src.Value);
    cbMinEdit.Callback = @(src, ~) updateColorLimits(app.figure, 'min', str2double(src.String));
    cbMaxEdit.Callback = @(src, ~) updateColorLimits(app.figure, 'max', str2double(src.String));
    alphaSlider.Callback = @(~, ~) applyMaskAlphasAndTOF(app.figure);
    syncCheckbox.Callback = @(~, ~) applyMaskAlphas(app.figure);
    atlasCheckbox.Callback = @(src, ~) toggleAtlasOverlay(app.figure, logical(src.Value));
    atlasAlphaSlider.Callback = @(src, ~) updateAtlasOverlay(app.figure);
    focusButton.Callback = @(~,~) focusOnSelectedLOC(app.figure);
    resetButton.Callback = @(~,~) resetView(app.figure);

    scatterAll.ButtonDownFcn = @(src, evt) onScatterClick(app.figure, src, evt);
    scatterSel.ButtonDownFcn = @(src, evt) onScatterClick(app.figure, src, evt);

    applyParameterSelection(app.figure, 1, true);
    updateSelection(app.figure, 1, vesselNames, locKeys);
    applyMaskAlphas(app.figure);
    updateAtlasOverlay(app.figure);
    
    % Ensure scatter plots are on top for click detection
    appData = guidata(app.figure);
    if isfield(appData, 'scatterAll') && isgraphics(appData.scatterAll)
        uistack(appData.scatterAll, 'top');
    end
    if isfield(appData, 'scatterSel') && isgraphics(appData.scatterSel)
        uistack(appData.scatterSel, 'top');
    end
    if isfield(appData, 'cursorMarker') && isgraphics(appData.cursorMarker)
        uistack(appData.cursorMarker, 'top');
    end

    waitfor(app.figure);
end

function locInfo = computeLocInfo(locKeys, LOCs, data_struct)
    locInfo = struct('key', {}, 'segment', {}, 'clIndex', {}, ...
                     'rowIdx', {}, 'coord', {}, 'flow', {}, ...
                     'PI', {}, 'RI', {});
    branchList = data_struct.branchList;
    for i = 1:numel(locKeys)
        key = locKeys{i};
        entry = LOCs.(key);
        segID = entry(1);
        clIdx = entry(2);
        matchRows = find(branchList(:,4) == segID & branchList(:,5) == clIdx, 1);
        if isempty(matchRows)
            warning('paramMap_GUI:MissingBranchRow', ...
                    'No branchList row found for %s (segment %d, index %d).', ...
                    key, segID, clIdx);
            continue;
        end
        locInfo(end+1).key = key; 
        locInfo(end).segment = segID;
        locInfo(end).clIndex = clIdx;
        locInfo(end).rowIdx = matchRows;
        locInfo(end).coord = branchList(matchRows, 1:3);
        locInfo(end).flow = data_struct.flowPerHeartCycle_val(matchRows);
        locInfo(end).PI = data_struct.PI_val(matchRows);
        locInfo(end).RI = data_struct.RI_val(matchRows);
    end
end

function names = buildDisplayNames(keys)
    pretty = containers.Map( ...
        {'LICA','RICA','BASI','LMCA','RMCA','LACA','RACA', ...
         'LPCA','RPCA','SSSV','LTSV','RTSV','STRV','COMM'}, ...
        {'Left ICA','Right ICA','Basilar', ...
         'Left MCA','Right MCA','Left ACA','Right ACA', ...
         'Left PCA','Right PCA','Superior Sagittal Sinus', ...
         'Left Transverse Sinus','Right Transverse Sinus','Straight Sinus','Communicating'} ...
    );
    names = cell(size(keys));
    for i = 1:numel(keys)
        key = keys{i};
        if pretty.isKey(key)
            names{i} = pretty(key);
        else
            names{i} = key;
        end
    end
end

function [surfacePatches, scatterAll, scatterSel] = plotCenterlines(ax, data_struct, correspondenceDict, multiQVTvol)
    % Generate colored isosurfaces for each vessel
    % Note: isosurface() creates a mesh from the voxel data. The visual smoothness
    % is determined by the voxel resolution and the lighting method.
    % We use 'flat' lighting in the main function to show the faceted structure.
    surfacePatches = struct('handle', {}, 'label', {}, 'vessel', {});

    % Define distinct colors for each vessel type
    vesselColors = containers.Map(...
        {'LICA', 'RICA', 'BASI', 'LMCA', 'RMCA', 'LACA', 'RACA', ...
         'LPCA', 'RPCA', 'SSSV', 'LTSV', 'RTSV', 'STRV', 'COMM'}, ...
        {[1 0.2 0.2], [0.2 0.2 1], [0.2 1 0.2], [1 0.6 0.2], [0.6 0.2 1], ...
         [1 0.8 0.2], [0.8 0.2 1], [0.2 1 0.8], [0.2 0.8 1], ...
         [1 0.4 0.6], [0.4 1 0.6], [0.6 0.4 1], [0.8 0.8 0.2], [0.5 0.5 0.5]});

    % Use multilabel volume if available, otherwise use binary segment
    if ~isempty(multiQVTvol) && ~all(multiQVTvol(:) == 0)
        segVol = permute(multiQVTvol, [2 1 3]);
        uniqueLabels = unique(segVol(segVol > 0));

        % Map labels to vessel names using a Voting Scheme (Majority Rule)
        % This prevents a single stray point from stealing an entire vessel label.
        
        % 1. Tally votes: voteMatrix(labelID, vesselIndex) = count
        vesselKeys = fieldnames(correspondenceDict);
        maxLabel = max(segVol(:));
        if isempty(maxLabel) || maxLabel == 0
            maxLabel = 0;
        end
        voteMatrix = zeros(maxLabel, numel(vesselKeys));
        
        for i = 1:numel(vesselKeys)
            key = vesselKeys{i};
            segments = correspondenceDict.(key);
            for seg = segments(:)'
                branchMask = data_struct.branchList(:,4) == seg;
                if any(branchMask)
                    % Extract coords and match the permutation used for segVol
                    coords = round(data_struct.branchList(branchMask, 1:3));
                    coordsPerm = [coords(:,2), coords(:,1), coords(:,3)];
                    
                    validCoords = coordsPerm(:,1) >= 1 & coordsPerm(:,1) <= size(segVol,1) & ...
                                  coordsPerm(:,2) >= 1 & coordsPerm(:,2) <= size(segVol,2) & ...
                                  coordsPerm(:,3) >= 1 & coordsPerm(:,3) <= size(segVol,3);
                    
                    if any(validCoords)
                        linearIdx = sub2ind(size(segVol), ...
                            coordsPerm(validCoords,1), ...
                            coordsPerm(validCoords,2), ...
                            coordsPerm(validCoords,3));
                        
                        foundLabels = segVol(linearIdx);
                        foundLabels = foundLabels(foundLabels > 0);
                        
                        % Add counts to the matrix
                        if ~isempty(foundLabels)
                            uniLabels = unique(foundLabels);
                            for u = uniLabels(:)'
                                voteMatrix(u, i) = voteMatrix(u, i) + sum(foundLabels == u);
                            end
                        end
                    end
                end
            end
        end

        % 2. Assign labels to the winning vessel
        labelToVessel = containers.Map('KeyType', 'double', 'ValueType', 'char');
        for lbl = 1:maxLabel
            [maxVotes, winnerIdx] = max(voteMatrix(lbl, :));
            % Threshold: Optional, ensure at least >1 point supports this
            if maxVotes > 0 
                labelToVessel(lbl) = vesselKeys{winnerIdx};
            end
        end

        % Create isosurface for each unique label
        for lbl = uniqueLabels(:)'
            if isKey(labelToVessel, lbl)
                vesselName = labelToVessel(lbl);
                if vesselColors.isKey(vesselName)
                    color = vesselColors(vesselName);
                else
                    color = [0.7 0.7 0.7];
                end
            else
                vesselName = '';
                color = [0.7 0.7 0.7];
            end

            try
                maskVol = (segVol == lbl);
                if any(maskVol(:))
                    fv = isosurface(maskVol, 0.5);
                    if ~isempty(fv.vertices)
                        patchHandle = patch(ax, fv, ...
                            'FaceColor', color, ...
                            'EdgeColor', 'none', ...
                            'FaceAlpha', 0.5, ...
                            'HitTest', 'off', ...
                            'PickableParts', 'none');
                        surfacePatches(end+1) = struct( ... %#ok<AGROW>
                            'handle', patchHandle, ...
                            'label', lbl, ...
                            'vessel', vesselName);
                    end
                end
            catch ME
                warning('paramMap_GUI:IsosurfaceLabelFailed', ...
                        'Could not generate isosurface for label %d: %s', lbl, ME.message);
            end
        end
    else
        % Fallback to binary segment with single gray isosurface
        segVol = permute(data_struct.segment, [2 1 3]);
        try
            fv = isosurface(segVol, 0.5);
            if ~isempty(fv.vertices)
                patchHandle = patch(ax, fv, ...
                    'FaceColor', [0.8 0.8 0.8], ...
                    'EdgeColor', 'none', ...
                    'FaceAlpha', 0.5, ...
                    'HitTest', 'off', ...
                    'PickableParts', 'none');
                surfacePatches(1) = struct( ...
                    'handle', patchHandle, ...
                    'label', 0, ...
                    'vessel', '');
            end
        catch ME
            warning('paramMap_GUI:IsosurfaceFailed', ...
                    'Could not generate isosurface: %s', ME.message);
        end
    end

    branchList = data_struct.branchList(:, 1:3);
    flowVals = data_struct.flowPerHeartCycle_val;

    scatterAll = scatter3(ax, branchList(:,1), branchList(:,2), branchList(:,3), ...
                          16, flowVals, 'filled', ...
                          'MarkerFaceAlpha', 0.8, ...
                          'MarkerEdgeAlpha', 0.8, ...
                          'PickableParts', 'all', ...
                          'HitTest', 'on');
    scatterSel = scatter3(ax, NaN, NaN, NaN, ...
                          40, [1 0 0], 'filled', ...
                          'MarkerEdgeColor', 'k', ...
                          'Visible', 'off', ...
                          'PickableParts', 'all', ...
                          'HitTest', 'on');
    
    % Initialize vector plot as a PATCH object for colored lines
    % We use a patch with NaN separators or explicit faces to draw lines.
    % Vertices will be updated in updateVectors.
    % We also add a scatter3 for "arrow heads" or just rely on lines for now.
    % To show direction, maybe just lines is not enough. 
    % Let's add a second scatter plot for the "Heads" of the vectors.
    
    vectorShafts = patch(ax, ...
                         'XData', [NaN NaN], 'YData', [NaN NaN], 'ZData', [NaN NaN], ...
                         'CData', [NaN NaN], ...
                         'EdgeColor', 'interp', ...
                         'LineWidth', 2, ...
                         'Visible', 'off', ...
                         'HitTest', 'off', ...
                         'PickableParts', 'none');
                     
    % We can use a cone marker for heads if we want, or just lines. 
    % Let's stick to colored lines (shafts) first as it's efficient.
    % If arrows are needed, we can add a scatter with 'v' or similar, rotated? Hard.
    % Simple solution: Just colored lines for now, user asked for "vectors ... colored".
    % Standard quiver3 cannot do this efficiently.
    
    scatterAll.UserData.vectorShafts = vectorShafts;
    
    % Store handle in axes appdata or output struct?
end

function locPlots = plotLocMarkers(ax, locInfo)
    if isempty(locInfo)
        locPlots.all = scatter3(ax, NaN, NaN, NaN, 80, 'w', 'filled', ...
                                'HitTest', 'off', 'PickableParts', 'none');
        locPlots.sel = scatter3(ax, NaN, NaN, NaN, 180, 'y', 'filled', ...
                                'MarkerEdgeColor', 'k', ...
                                'HitTest', 'off', 'PickableParts', 'none');
        return;
    end
    coords = vertcat(locInfo.coord);
    locPlots.all = scatter3(ax, coords(:,1), coords(:,2), coords(:,3), ...
                            90, 'w', 'filled', ...
                            'MarkerEdgeColor', [0 0 0], ...
                            'LineWidth', 0.5, ...
                            'HitTest', 'off', ...
                            'PickableParts', 'none');
    locPlots.sel = scatter3(ax, NaN, NaN, NaN, ...
                            220, 'y', 'filled', ...
                            'MarkerEdgeColor', 'k', ...
                            'LineWidth', 1.5, ...
                            'Visible', 'off', ...
                            'HitTest', 'off', ...
                            'PickableParts', 'none');
end

function paramOptions = createParamOptions(data_struct)
    paramOptions = struct('label', {}, 'field', {}, 'units', {}, 'customData', {});
    nPoints = size(data_struct.branchList, 1);
    preferred = {
        'area_val',            'Cross-sectional Area', 'cm^2';
        'diam_val',            'Area Ratio',           '';
        'flowPerHeartCycle_val','Total Flow',          'mL/s';
        'maxVel_val',          'Maximum Velocity',     'cm/s';
        'velMean_val',         'Mean Velocity',        'cm/s';
        'StdvFromMean',        'Flow Consistency',     '';
        'RI_val',              'Resistance Index',     '';
        'PI_val',              'Pulsatility Index',    ''
    };

    added = {};
    for i = 1:size(preferred,1)
        field = preferred{i,1};
        if isfield(data_struct, field) && numel(data_struct.(field)) == nPoints
            paramOptions(end+1) = struct( ...
                'label', preferred{i,2}, ...
                'field', field, ...
                'units', preferred{i,3}, ...
                'customData', []); %#ok<AGROW>
            added{end+1} = field; %#ok<AGROW>
        end
    end

    dataFields = fieldnames(data_struct);
    for i = 1:numel(dataFields)
        field = dataFields{i};
        if ismember(field, added)
            continue;
        end
        vals = data_struct.(field);
        if isnumeric(vals) && isvector(vals) && numel(vals) == nPoints
            label = strrep(field, '_', ' ');
            label = regexprep(label, '(\<[a-z])', '${upper($1)}');
            paramOptions(end+1) = struct( ...
                'label', label, ...
                'field', field, ...
                'units', '', ...
                'customData', []);
            added{end+1} = field; %#ok<AGROW>
        end
    end

    if isfield(data_struct, 'flowPulsatile_val')
        meanFlow = mean(data_struct.flowPulsatile_val, 2, 'omitnan');
        if numel(meanFlow) == nPoints
            paramOptions(end+1) = struct( ...
                'label', 'Mean Flow (Point)', ...
                'field', '', ...
                'units', 'mL/s', ...
                'customData', meanFlow(:));
        end
    end

    if isempty(paramOptions)
        paramOptions = struct('label', 'Total Flow', ...
                              'field', 'flowPerHeartCycle_val', ...
                              'units', 'mL/s', ...
                              'customData', []);
    end
end

function setupCrossAxes(ax, titleText)
    imagesc(ax, zeros(10)); %#ok<MCSUP>
    axis(ax, 'image');
    axis(ax, 'off');
    colormap(ax, gray);
    title(ax, titleText, 'Color', 'k', 'FontSize', 10);
end

function prepareWaveformAxes(ax)
    hold(ax, 'on');
    ax.XColor = [0 0 0];
    ax.YColor = [0 0 0];
    ax.Color = [1 1 1];
end

function applyParameterSelection(fig, idx, resetLimits)
    appData = guidata(fig);
    option = appData.paramOptions(idx);
    if isfield(option, 'customData') && ~isempty(option.customData)
        data = double(option.customData);
    else
        data = double(appData.data_struct.(option.field));
    end
    appData.currentParamIndex = idx;
    appData.paramData = data;
    appData.paramLabel = option.label;
    appData.paramUnits = option.units;
    guidata(fig, appData);

    scatterAll = appData.scatterAll;
    scatterAll.CData = data;

    if strcmpi(appData.paramUnits, '')
        appData.colorbar.Label.String = option.label;
    else
        appData.colorbar.Label.String = sprintf('%s (%s)', option.label, appData.paramUnits);
    end

    finiteVals = data(isfinite(data));
    if isempty(finiteVals)
        finiteVals = [0 1];
    end
    minVal = min(finiteVals);
    maxVal = max(finiteVals);
    if resetLimits || any(~isfinite(caxis(appData.axes)))
        caxis(appData.axes, [minVal maxVal]);
    end
    limits = caxis(appData.axes);
    appData.cbMinEdit.String = sprintf('%.3f', limits(1));
    appData.cbMaxEdit.String = sprintf('%.3f', limits(2));

    if ~isempty(appData.selection.selIndices)
        appData.scatterSel.CData = data(appData.selection.selIndices);
    end

    guidata(fig, appData);
end

function updateSelection(fig, selectionIdx, vesselNames, locKeys)
    appData = guidata(fig);
    scatterAll = appData.scatterAll;
    scatterSel = appData.scatterSel;
    locPlots = appData.locPlots;
    branchList = appData.branchList;
    correspondenceDict = appData.correspondenceDict;
    locInfo = appData.locInfo;

    scatterSel.Visible = 'off';
    locPlots.sel.Visible = 'off';
    appData.selection.key = '';
    appData.selection.locIndex = [];
    appData.selection.selIndices = [];
    appData.selection.pointRow = [];
    appData.cursorMarker.Visible = 'off';
    hidePlaneOverlay(fig);
    updateInfoBox(fig, [], []);

    scatterAll.MarkerFaceAlpha = 0.8;
    scatterAll.MarkerEdgeAlpha = 0.8;
    scatterAll.CData = appData.paramData;

    if selectionIdx <= 1 || isempty(vesselNames)
        scatterAll.Visible = 'on';
        guidata(fig, appData);
        applyMaskAlphas(fig);
        return;
    end

    key = locKeys{selectionIdx-1};
    appData.selection.key = key;

    segments = [];
    if isfield(correspondenceDict, key)
        segments = unique(correspondenceDict.(key));
    elseif strcmpi(key, 'COMM') && isfield(correspondenceDict, 'COMM')
        segments = unique(correspondenceDict.COMM);
    end

    segMask = ismember(branchList(:,4), segments);
    if ~any(segMask)
        warning('paramMap_GUI:EmptySegment', ...
                'No centerline points found for vessel %s.', key);
        guidata(fig, appData);
        hidePlaneOverlay(fig);
        return;
    end

    scatterAll.MarkerFaceAlpha = 0.05;
    scatterAll.MarkerEdgeAlpha = 0.05;

    scatterSel.Visible = 'on';
    scatterSel.XData = branchList(segMask, 1);
    scatterSel.YData = branchList(segMask, 2);
    scatterSel.ZData = branchList(segMask, 3);
    scatterSel.CData = appData.paramData(segMask);

    appData.selection.selIndices = find(segMask);

    locIdx = find(strcmp({locInfo.key}, key), 1);
    if ~isempty(locIdx)
        appData.selection.locIndex = locIdx;
        locEntry = locInfo(locIdx);
        locPlots.sel.Visible = 'on';
        locPlots.sel.XData = locEntry.coord(1);
        locPlots.sel.YData = locEntry.coord(2);
        locPlots.sel.ZData = locEntry.coord(3);
        updateInfoBox(fig, key, locEntry);
        updateSelectedPoint(fig, locEntry.rowIdx);
    else
        updateInfoBox(fig, key, []);
    end

    guidata(fig, appData);
    applyMaskAlphas(fig);
end

function updateInfoBox(fig, key, locEntry)
    appData = guidata(fig);
    infoBox = appData.infoBox;
    if isempty(key)
        infoBox.String = sprintf('Select a vessel to inspect centerline points and LOCs.\nClick any point in the 3D view to inspect its cross-section.');
        return;
    end

    pretty = buildDisplayNames({key});
    label = pretty{1};

    if isempty(locEntry)
        infoBox.String = sprintf('Vessel: %s\nNo LOC data available.', label);
        return;
    end

    paramVal = appData.paramData(locEntry.rowIdx);
    if isempty(appData.paramUnits)
        paramLine = sprintf('%s: %.3f', appData.paramLabel, paramVal);
    else
        paramLine = sprintf('%s: %.3f %s', appData.paramLabel, paramVal, appData.paramUnits);
    end

    infoBox.String = sprintf(['Vessel: %s\n' ...
                              'Segment ID: %d\n' ...
                              'Centerline Index: %d\n' ...
                              'Mean Flow: %.3f mL/s\n' ...
                              'PI: %.3f\n' ...
                              'RI: %.3f\n' ...
                              '%s'], ...
                              label, locEntry.segment, locEntry.clIndex, ...
                              locEntry.flow, locEntry.PI, locEntry.RI, paramLine);
end

function changeParameter(fig, newIndex)
    % Stop animation if running
    appData = guidata(fig);
    if appData.isAnimating
        toggleAnimation(fig, appData.playButton); 
        % Re-fetch appData as toggleAnimation updates it
        appData = guidata(fig);
    end

    applyParameterSelection(fig, newIndex, true);
    % After changing parameter, update color limits to match THIS parameter's range
    % The applyParameterSelection function handles caxis update if resetLimits=true.
    % We ensured resetLimits=true above.
    % But we need to make sure we don't accidentally stick to globalFlowRange.
    % applyParameterSelection does: caxis(appData.axes, [minVal maxVal]);
    % This is correct for static params.
    
    guidata(fig, appData);
end
%         scatterSel = appData.scatterSel;
%         scatterSel.CData = appData.paramData(appData.selection.selIndices);
%     end
%     if ~isempty(appData.selection.locIndex)
%         locEntry = appData.locInfo(appData.selection.locIndex);
%         updateInfoBox(fig, appData.selection.key, locEntry);
%     end
%     if ~isempty(appData.selection.pointRow)
%         displayPointInfo(fig, appData.selection.pointRow);
%     end
%     guidata(fig, appData);
% end

function changeColormap(fig, idx)
    appData = guidata(fig);
    cmap = appData.colormapList{idx};
    colormap(appData.axes, cmap);
end

function updateColorLimits(fig, whichLimit, value)
    appData = guidata(fig);
    if ~isfinite(value)
        return;
    end
    limits = caxis(appData.axes);
    switch whichLimit
        case 'min'
            limits(1) = value;
        case 'max'
            limits(2) = value;
    end
    if limits(1) >= limits(2)
        limits(2) = limits(1) + eps;
    end
    caxis(appData.axes, limits);
    appData.cbMinEdit.String = sprintf('%.3f', limits(1));
    appData.cbMaxEdit.String = sprintf('%.3f', limits(2));
    guidata(fig, appData);
end

function focusOnSelectedLOC(fig)
    appData = guidata(fig);
    if isempty(appData.selection.key) || isempty(appData.selection.locIndex)
        return;
    end
    locEntry = appData.locInfo(appData.selection.locIndex);
    target = locEntry.coord;
    margin = 10;
    ax = appData.axes;
    xlim(ax, target(1) + margin * [-1 1]);
    ylim(ax, target(2) + margin * [-1 1]);
    zlim(ax, target(3) + margin * [-1 1]);
    camtarget(ax, target);
    updateSelectedPoint(fig, locEntry.rowIdx);
end

function resetView(fig)
    appData = guidata(fig);
    ax = appData.axes;
    axis(ax, 'auto');
    axis(ax, 'equal');
    try
        camlight(ax, 'headlight');
    catch ME
        warning('paramMap_GUI:CamlightReset','camlight failed during reset: %s', ME.message);
    end
    lighting(ax, 'flat');
    applyParameterSelection(fig, appData.currentParamIndex, false);
    guidata(fig, appData);
end

function onScatterClick(fig, src, evt)
    selType = get(fig,'SelectionType');
    isShiftSelect = strcmpi(selType, 'extend'); % 'extend' = Shift+click
    if ~strcmp(selType,'normal') && ~isShiftSelect
        return;
    end
    appData = guidata(fig);
    idx = [];

    if ~isempty(evt)
        if isprop(evt,'DataIndex') && ~isempty(evt.DataIndex) && evt.DataIndex > 0
            if src == appData.scatterSel && ~isempty(appData.selection.selIndices)
                idx = appData.selection.selIndices(evt.DataIndex);
            else
                idx = evt.DataIndex;
            end
        elseif isprop(evt,'IntersectionPoint') && ~isempty(evt.IntersectionPoint)
            idx = nearestBranchIndex(appData, evt.IntersectionPoint);
        end
    end

    if isempty(idx)
        pos = get(appData.axes, 'CurrentPoint');
        idx = nearestBranchIndex(appData, pos(1,1:3));
    end

    if ~isempty(idx) && idx > 0
        updateSelectedPoint(fig, idx);
        if isShiftSelect
            syncSelectionToVessel(fig, idx);
        end
    end
end

function updateSelectedPoint(fig, rowIdx)
    appData = guidata(fig);
    if rowIdx < 1 || rowIdx > size(appData.branchList,1)
        return;
    end
    coord = appData.branchList(rowIdx, 1:3);
    appData.cursorMarker.Visible = 'on';
    appData.cursorMarker.XData = coord(1);
    appData.cursorMarker.YData = coord(2);
    appData.cursorMarker.ZData = coord(3);
    appData.selection.pointRow = rowIdx;
    guidata(fig, appData);
    displayPointInfo(fig, rowIdx);
    updateCrossSections(fig, rowIdx);
    updateWaveform(fig, rowIdx);
    updatePlaneOverlay(fig, rowIdx);
    update3DViews(fig, rowIdx);
end

function update3DViews(fig, rowIdx)
    appData = guidata(fig);
    coord = appData.branchList(rowIdx, 1:3);
    r = 15; % Zoom radius
    
    % Coronal View (XZ)
    ax = appData.axesCor;
    copyobj(appData.axes.Children, ax);
    axis(ax, 'equal'); axis(ax, 'off');
    xlim(ax, coord(1) + [-r r]);
    ylim(ax, coord(2) + [-r r]);
    zlim(ax, coord(3) + [-r r]);
    view(ax, [0 0]); 
    title(ax, 'Coronal', 'Color', 'k', 'FontSize', 8);
    
    % Axial View (XY)
    ax = appData.axesAx;
    copyobj(appData.axes.Children, ax);
    axis(ax, 'equal'); axis(ax, 'off');
    xlim(ax, coord(1) + [-r r]);
    ylim(ax, coord(2) + [-r r]);
    zlim(ax, coord(3) + [-r r]);
    view(ax, [0 90]);
    title(ax, 'Axial', 'Color', 'k', 'FontSize', 8);
    
    % 3D Zoom
    ax = appData.axesZoom;
    copyobj(appData.axes.Children, ax);
    axis(ax, 'equal'); axis(ax, 'off');
    xlim(ax, coord(1) + [-r r]);
    ylim(ax, coord(2) + [-r r]);
    zlim(ax, coord(3) + [-r r]);
    view(ax, 3);
    camlight(ax, 'headlight'); lighting(ax, 'flat');
    title(ax, '3D Zoom', 'Color', 'k', 'FontSize', 8);
end

function displayPointInfo(fig, rowIdx)
    appData = guidata(fig);
    if isempty(rowIdx)
        return;
    end
    paramVal = appData.paramData(rowIdx);
    if strcmpi(appData.paramUnits, '')
        paramLine = sprintf('%s: %.3f', appData.paramLabel, paramVal);
    else
        paramLine = sprintf('%s: %.3f %s', appData.paramLabel, paramVal, appData.paramUnits);
    end
    segID = appData.branchList(rowIdx, 4);
    clIdx = appData.branchList(rowIdx, 5);
    flowVal = appData.flowPerHeartCycle_val(rowIdx);
    piVal = appData.PI_val(rowIdx);
    riVal = appData.RI_val(rowIdx);
    infoBox = appData.infoBox;
    infoBox.String = sprintf(['Selected Point\n' ...
                              'Segment ID: %d\n' ...
                              'Centerline Index: %d\n' ...
                              'Flow: %.3f mL/s\n' ...
                              'PI: %.3f\n' ...
                              'RI: %.3f\n' ...
                              '%s'], ...
                              segID, clIdx, flowVal, piVal, riVal, paramLine);
end

function updateCrossSections(fig, rowIdx)
    appData = guidata(fig);
    imdim = appData.imdim;
    mask = reshape(appData.segmentFull(rowIdx,:), imdim, imdim);
    mag = reshape(appData.MAGcrossection(rowIdx,:), imdim, imdim);
    cd = reshape(appData.timeMIPcrossection(rowIdx,:), imdim, imdim);
    velTA = reshape(appData.vTimeFrameave(rowIdx,:), imdim, imdim);

    v1 = squeeze(appData.VplanesAllx(rowIdx,:,:));
    v2 = squeeze(appData.VplanesAlly(rowIdx,:,:));
    v3 = squeeze(appData.VplanesAllz(rowIdx,:,:));
    VcrossTR = 0.1*(v1 + v2 + v3); % mm/s -> cm/s
    normDim = sqrt(size(VcrossTR,1));
    VcrossTR = reshape(VcrossTR, normDim, normDim, appData.nframes);
    VcrossTR = imresize(VcrossTR(:,:,peakFrameIndex(appData.flowPulsatile(rowIdx,:))), [imdim imdim], 'nearest');

    showCrossSection(appData.axesMAG, mag, mask, 'gray', 'Magnitude');
    showCrossSection(appData.axesCD, cd, mask, 'gray', 'Complex Difference');
    showCrossSection(appData.axesVelTA, velTA, mask, 'gray', 'Velocity (TA)');
    showCrossSection(appData.axesVelTR, VcrossTR, mask, 'gray', 'Velocity (TR)');
end

function idx = peakFrameIndex(flowWaveform)
    [~, idx] = max(abs(flowWaveform));
end

function showCrossSection(ax, imageData, mask, cmapName, titleText)
    axes(ax); %#ok<LAXES>
    cla(ax);
    imagesc(ax, imageData);
    axis(ax, 'image');
    axis(ax, 'off');
    colormap(ax, cmapName);
    hold(ax, 'on');
    contour(ax, mask, [0.5 0.5], 'LineWidth', 0.8, 'LineColor', 'w');
    hold(ax, 'off');
    title(ax, titleText, 'Color', 'k', 'FontSize', 10);
end

function updateWaveform(fig, rowIdx)
    appData = guidata(fig);
    ax = appData.axesWave;
    cla(ax);
    prepareWaveformAxes(ax);
    frames = 0:(appData.nframes-1);
    branchId = appData.branchList(rowIdx,4);
    branchMask = appData.branchList(:,4) == branchId;
    branchIndices = find(branchMask);
    [~, order] = sort(appData.branchList(branchMask,5));
    sortedIdx = branchIndices(order);
    pos = find(sortedIdx == rowIdx);
    neighborRange = max(pos-2,1):min(pos+2, numel(sortedIdx));
    neighborIdxs = sortedIdx(neighborRange);

    colorsPrev = {[0.85 0.3 0.3], [0.6 0 0]};
    colorsNext = {[0.2 0.85 0.2], [0 0.5 0]};
    baseline = [];
    for i = 1:numel(neighborIdxs)
        w = appData.flowPulsatile(neighborIdxs(i),:);
        neighborPos = find(sortedIdx == neighborIdxs(i), 1, 'first');
        offset = neighborPos - pos;
        if neighborIdxs(i) == rowIdx
            baseline = w;
            continue;
        end
        if offset < 0
            clr = colorsPrev{min(abs(offset), numel(colorsPrev))};
        else
            clr = colorsNext{min(offset, numel(colorsNext))};
        end
        plot(ax, frames, w, 'Color', clr, 'LineWidth', 1.1, 'LineStyle', '--');
    end
    if isempty(baseline)
        baseline = appData.flowPulsatile(rowIdx,:);
    end
    plot(ax, frames, baseline, 'Color', [0.1 0.7 1], 'LineWidth', 2.2);
    grid(ax, 'on');
    ax.GridColor = [0.8 0.8 0.8];
    ax.GridAlpha = 0.5;
    xlim(ax, [0 appData.nframes-1]);
    xticks(ax, frames);
    xlabel(ax, 'Cardiac Frame', 'Color', 'k');
    ylabel(ax, 'Flow (mL/s)', 'Color', 'k');
    title(ax, 'Time-Resolved Flow', 'Color', 'k');
end

function updatePlaneOverlay(fig, rowIdx)
    appData = guidata(fig);
    if ~isfield(appData, 'planeLines') || isempty(appData.planeLines) || ...
       ~isfield(appData, 'Planes') || isempty(appData.Planes)
        return;
    end
    if rowIdx < 1 || rowIdx > size(appData.Planes, 1)
        hidePlaneOverlay(fig);
        return;
    end
    planeCoords = squeeze(appData.Planes(rowIdx,:,:));
    if size(planeCoords,1) < 4
        hidePlaneOverlay(fig);
        return;
    end

    centerPt = mean(planeCoords, 1);
    shrinkFactor = 0.7;
    planeCoords = centerPt + shrinkFactor * (planeCoords - centerPt);

    if isfield(appData, 'planePatch') && isgraphics(appData.planePatch)
        set(appData.planePatch, 'Vertices', planeCoords, 'Visible', 'on');
        % Ensure scatter plots and cursor marker are on top for click detection
        if isfield(appData, 'scatterAll') && isgraphics(appData.scatterAll)
            uistack(appData.scatterAll, 'top');
        end
        if isfield(appData, 'scatterSel') && isgraphics(appData.scatterSel)
            uistack(appData.scatterSel, 'top');
        end
        if isfield(appData, 'cursorMarker') && isgraphics(appData.cursorMarker)
            uistack(appData.cursorMarker, 'top');
        end
    end

    edges = [1 2; 2 3; 3 4; 4 1];
    for e = 1:4
        lineHandle = appData.planeLines(e);
        if ~isgraphics(lineHandle)
            continue;
        end
        pts = planeCoords(edges(e,:), :);
        set(lineHandle, ...
            'XData', pts(:,1), ...
            'YData', pts(:,2), ...
            'ZData', pts(:,3), ...
            'Visible', 'on');
    end

    if isfield(appData, 'planeNormal') && isgraphics(appData.planeNormal)
        v1 = planeCoords(2,:) - planeCoords(1,:);
        v2 = planeCoords(4,:) - planeCoords(1,:);
        normalVec = cross(v1, v2);
        nNorm = norm(normalVec);
        if nNorm > 0
            normalVec = normalVec / nNorm;
        end
        edgeVecs = planeCoords([2 3 4 1],:) - planeCoords([1 2 3 4],:);
        edgeLens = vecnorm(edgeVecs, 2, 2);
        planeScale = mean(edgeLens);
        arrowLen = planeScale * 0.45;
        normalVec = normalVec * arrowLen;
        set(appData.planeNormal, ...
            'XData', centerPt(1), ...
            'YData', centerPt(2), ...
            'ZData', centerPt(3), ...
            'UData', normalVec(1), ...
            'VData', normalVec(2), ...
            'WData', normalVec(3), ...
            'Visible', 'on');
    end
end

function hidePlaneOverlay(fig)
    appData = guidata(fig);
    if isfield(appData, 'planeLines') && ~isempty(appData.planeLines)
        for e = 1:numel(appData.planeLines)
            lineHandle = appData.planeLines(e);
            if isgraphics(lineHandle)
                set(lineHandle, ...
                    'XData', [NaN NaN], ...
                    'YData', [NaN NaN], ...
                    'ZData', [NaN NaN], ...
                    'Visible', 'off');
            end
        end
    end
    if isfield(appData, 'planePatch') && isgraphics(appData.planePatch)
        set(appData.planePatch, 'Visible', 'off');
    end
    if isfield(appData, 'planeNormal') && isgraphics(appData.planeNormal)
        set(appData.planeNormal, ...
            'XData', NaN, 'YData', NaN, 'ZData', NaN, ...
            'UData', 0, 'VData', 0, 'WData', 0, ...
            'Visible', 'off');
    end
    if isfield(appData, 'planeNormalTip') && isgraphics(appData.planeNormalTip)
        set(appData.planeNormalTip, ...
            'XData', NaN, 'YData', NaN, 'ZData', NaN, ...
            'Visible', 'off');
    end
end

function applyMaskAlphas(fig)
    appData = guidata(fig);
    if ~isfield(appData, 'surfacePatches') || isempty(appData.surfacePatches)
        return;
    end
    if ~isfield(appData, 'alphaSlider') || ~ishandle(appData.alphaSlider)
        return;
    end
    alphaValue = appData.alphaSlider.Value;
    syncOn = isfield(appData, 'syncCheckbox') && ishandle(appData.syncCheckbox) && logical(appData.syncCheckbox.Value);
    selectedKey = '';
    if isfield(appData, 'selection') && isfield(appData.selection, 'key')
        selectedKey = appData.selection.key;
    end
    for i = 1:numel(appData.surfacePatches)
        try
            patchHandle = appData.surfacePatches(i).handle;
            if ~(ishandle(patchHandle) || (isobject(patchHandle) && isvalid(patchHandle)))
                continue;
            end
            targetAlpha = alphaValue;
            if syncOn && ~isempty(selectedKey)
                vesselName = appData.surfacePatches(i).vessel;
                if isempty(vesselName) || ~strcmpi(vesselName, selectedKey)
                    targetAlpha = alphaValue * 0.08;
                end
            end
            patchHandle.FaceAlpha = max(0, min(1, targetAlpha));
        catch
            % Ignore invalid handles
        end
    end
end

function idx = nearestBranchIndex(appData, pos)
    coords = appData.branchList(:,1:3);
    dists = sum((coords - pos).^2, 2);
    [minDist, idx] = min(dists);
    if ~isfinite(minDist)
        idx = [];
    end
end

function applyMaskAlphasAndTOF(fig)
    applyMaskAlphas(fig);
end

function syncSelectionToVessel(fig, rowIdx)
    appData = guidata(fig);
    if rowIdx < 1 || rowIdx > size(appData.branchList,1)
        return;
    end
    segID = appData.branchList(rowIdx,4);
    vesselKey = findVesselKey(appData.correspondenceDict, segID);
    if isempty(vesselKey)
        return;
    end
    locIdx = find(strcmp(appData.locKeys, vesselKey), 1);
    if isempty(locIdx)
        return;
    end
    newValue = locIdx + 1; % account for "All Vessels"
    vesselNames = appData.vesselNames;
    locKeys = appData.locKeys;
    if appData.dropdown.Value ~= newValue
        appData.dropdown.Value = newValue;
        guidata(fig, appData);
        updateSelection(fig, newValue, vesselNames, locKeys);
    else
        updateSelection(fig, newValue, vesselNames, locKeys);
    end
end

function vesselKey = findVesselKey(correspondenceDict, segID)
    vesselKey = '';
    dictFields = fieldnames(correspondenceDict);
    for i = 1:numel(dictFields)
        key = dictFields{i};
        segments = correspondenceDict.(key);
        if isempty(segments)
            continue;
        end
        if any(segments == segID)
            vesselKey = key;
            return;
        end
    end
end

function toggleAtlasOverlay(fig, enabled)
    appData = guidata(fig);
    if ~isfield(appData, 'atlasVolume') || isempty(appData.atlasVolume)
        return;
    end
    appData.showAtlas = enabled;
    guidata(fig, appData);
    updateAtlasOverlay(fig);
end

function updateAtlasOverlay(fig)
    appData = guidata(fig);
    if ~isfield(appData, 'atlasVolume') || isempty(appData.atlasVolume)
        return;
    end
    enabled = isfield(appData, 'showAtlas') && appData.showAtlas;
    if ~enabled
        if isfield(appData, 'atlasPatches') && ~isempty(appData.atlasPatches)
            for i = 1:numel(appData.atlasPatches)
                h = appData.atlasPatches(i);
                if isgraphics(h)
                    set(h, 'Visible', 'off');
                end
            end
        end
        return;
    end
    segVol = permute(appData.atlasVolume, [2 1 3]);
    labels = unique(segVol(segVol > 0));
    if isempty(labels)
        return;
    end
    % If patches not built or labels changed, rebuild
    needRebuild = isempty(appData.atlasPatches) || ...
                  ~isfield(appData, 'atlasLabels') || ...
                  numel(appData.atlasLabels) ~= numel(labels) || ...
                  any(appData.atlasLabels(:)' ~= labels(:)');
    if needRebuild
        if isfield(appData, 'atlasPatches') && ~isempty(appData.atlasPatches)
            for i = 1:numel(appData.atlasPatches)
                if isgraphics(appData.atlasPatches(i))
                    delete(appData.atlasPatches(i));
                end
            end
        end
        % Get transparency from slider
        atlasAlpha = 0.18; % default
        if isfield(appData, 'atlasAlphaSlider') && isgraphics(appData.atlasAlphaSlider)
            atlasAlpha = appData.atlasAlphaSlider.Value;
        end
        
        colors = lines(numel(labels));
        atlasPatches = gobjects(numel(labels),1);
        for i = 1:numel(labels)
            mask = segVol == labels(i);
            if ~any(mask(:))
                continue;
            end
            try
                % Smooth to bridge gaps in small vessels
                % maskSmooth = smooth3(double(mask), 'box', 3);
                fv = isosurface(mask, 0.5);
            catch
                continue;
            end
            if isempty(fv.vertices)
                continue;
            end
            atlasPatches(i) = patch(appData.axes, fv, ...
                'FaceColor', colors(i,:), ...
                'EdgeColor', 'none', ...
                'FaceAlpha', atlasAlpha, ...
                'HitTest', 'off', ...
                'Visible', 'on');
        end
        valid = isgraphics(atlasPatches);
        atlasPatches = atlasPatches(valid);
        appData.atlasPatches = atlasPatches;
        appData.atlasLabels = labels(valid);
        guidata(fig, appData);
    else
        % Update transparency for existing patches
        atlasAlpha = 0.18; % default
        if isfield(appData, 'atlasAlphaSlider') && isgraphics(appData.atlasAlphaSlider)
            atlasAlpha = appData.atlasAlphaSlider.Value;
        end
        
        for i = 1:numel(appData.atlasPatches)
            h = appData.atlasPatches(i);
            if isgraphics(h)
                set(h, 'FaceAlpha', atlasAlpha, 'Visible', 'on');
            end
        end
    end
end

function toggleVectors(fig, show)
    appData = guidata(fig);
    if ~isfield(appData.scatterAll.UserData, 'vectorShafts')
        return;
    end
    vectorShafts = appData.scatterAll.UserData.vectorShafts;
    
    if show
        appData.scatterAll.Visible = 'off';
        vectorShafts.Visible = 'on';
        updateVectors(fig);
    else
        appData.scatterAll.Visible = 'on';
        vectorShafts.Visible = 'off';
    end
end

function updateVectors(fig)
    appData = guidata(fig);
    vectorShafts = appData.scatterAll.UserData.vectorShafts;
    if strcmp(vectorShafts.Visible, 'off')
            return;
    end
    
    % Get vector settings
    thickVal = str2double(appData.vecThickEdit.String);
    if isnan(thickVal) || thickVal <= 0, thickVal = 2.0; end
    
    scaleVal = str2double(appData.vecScaleEdit.String);
    if isnan(scaleVal) || scaleVal <= 0, scaleVal = 1.5; end
    
    set(vectorShafts, 'LineWidth', thickVal);
    
    % Get current data
    coords = appData.branchList(:, 1:3);
    tangents = appData.tangents;
    
    % Scale by current parameter (e.g. flow or velocity)
    if appData.isAnimating
        frame = appData.currentFrame;
        % User requested: "animated the flow itself ... absolute value have sense for this"
        % Stick to Flow Pulsatile but scale by Magnitude
        flowVals = appData.flowPulsatile(:, frame);
        globalRange = appData.globalFlowRange;
    else
        flowVals = appData.paramData;
        globalRange = [min(flowVals(:)), max(flowVals(:))];
    end
    
    % Handle NaN
    flowVals(isnan(flowVals)) = 0;
    
    % Use global max flow if available for consistent scaling (using Absolute Max)
    
    if ~isempty(globalRange)
        maxVal = max(abs(globalRange));
    else
        maxVal = max(abs(flowVals(:)));
    end
    if maxVal == 0, maxVal = 1; end
    
    % Length of vector in data units (approx voxel units?)
    % Use SIGNED value for length scaling to preserve direction/sense
    % If flow is negative (backward relative to centerline), vector should point backwards.
    % We previously used ABS which forced all arrows forward.
    % Reverting to SIGNED calculation for 'lenFactors'.
    % lenFactors = (abs(flowVals) / maxVal) * 5 * scaleVal; % OLD (Magnitude only)
    
    % We calculate signed factor, then apply to tangent.
    % This makes the vector point in the direction of flow.
    % lenFactors = (flowVals / maxVal) * 5 * scaleVal;
    
    % Calculate end points (tips)
    % Tangents point along centerline.
    % Flow value sign indicates direction relative to centerline tangent.
    % If flow > 0, vector = tangent * len.
    % If flow < 0, vector = tangent * (-len) = -tangent * |len|.
    % So multiplying tangent by SIGNED flow automatically handles forward/backward sense.
    
    % Use SIGNED flow for length factor direction
    % lenFactors magnitude is length, sign is direction
    lenFactors = (-flowVals / maxVal) * 5 * scaleVal; 
    
    % Calculate end points (tips)
    Tips = coords + tangents .* lenFactors;
    
    % --- Arrow Head Construction ---
    % Compute basis vectors U, V perpendicular to Tangents
    Ref = repmat([0 0 1], size(tangents,1), 1);
    isPar = abs(dot(tangents, Ref, 2)) > 0.99;
    Ref(isPar, :) = repmat([0 1 0], sum(isPar), 1);
    
    U = cross(tangents, Ref);
    % Normalize U
    uLen = sqrt(sum(U.^2, 2));
    U = U ./ (uLen + eps);
    
    V = cross(tangents, U);
    % Normalize V (should be already, but safe to ensure)
    vLen = sqrt(sum(V.^2, 2));
    V = V ./ (vLen + eps);
    
    % Arrow Head Dimensions
    headLen = lenFactors * 0.25;
    headWid = lenFactors * 0.1;
    
    % Base points of arrow head (Tripod shape)
    % 3 lines from Tip back to base points
    B1 = Tips - tangents.*headLen + U.*headWid;
    B2 = Tips - tangents.*headLen - U.*0.5.*headWid + V.*0.866.*headWid;
    B3 = Tips - tangents.*headLen - U.*0.5.*headWid - V.*0.866.*headWid;
    
    % Construct Patch Data (Shafts + Heads)
    n = size(coords, 1);
    nanSep = repmat(NaN, 1, n);
    
    % X coordinates
    X = [coords(:,1)'; Tips(:,1)'; nanSep; ...          % Shaft
         Tips(:,1)';   B1(:,1)';   nanSep; ...          % Head 1
         Tips(:,1)';   B2(:,1)';   nanSep; ...          % Head 2
         Tips(:,1)';   B3(:,1)';   nanSep];             % Head 3
    X = X(:);
    
    % Y coordinates
    Y = [coords(:,2)'; Tips(:,2)'; nanSep; ...
         Tips(:,2)';   B1(:,2)';   nanSep; ...
         Tips(:,2)';   B2(:,2)';   nanSep; ...
         Tips(:,2)';   B3(:,2)';   nanSep];
    Y = Y(:);
    
    % Z coordinates
    Z = [coords(:,3)'; Tips(:,3)'; nanSep; ...
         Tips(:,3)';   B1(:,3)';   nanSep; ...
         Tips(:,3)';   B2(:,3)';   nanSep; ...
         Tips(:,3)';   B3(:,3)';   nanSep];
    Z = Z(:);
    
    % Colors (match vertices)
    % Use ABSOLUTE value for coloring if animating (Magnitude)
    if appData.isAnimating
        colorData = abs(flowVals);
    else
        colorData = flowVals;
    end
    
    C_seg = [colorData'; colorData'; nanSep]; % 3 x n
    C = repmat(C_seg, 4, 1); % 12 x n
    C = C(:);
    
    set(vectorShafts, 'XData', X, 'YData', Y, 'ZData', Z, 'CData', C);
end

function toggleAnimation(fig, btn)
    appData = guidata(fig);
    if appData.isAnimating
        % Stop
        appData.isAnimating = false;
        btn.String = 'Play';
        if ~isempty(appData.timer)
            stop(appData.timer);
            delete(appData.timer);
            appData.timer = [];
        end
    else
        % Start
        appData.isAnimating = true;
        btn.String = 'Stop';
        appData.timer = timer('ExecutionMode', 'fixedRate', 'Period', 0.1, ...
                              'TimerFcn', @(~,~) updateAnimationLoop(fig));
        start(appData.timer);
    end
    guidata(fig, appData);
end

function updateAnimationLoop(fig)
    if ~isgraphics(fig)
        return;
    end
    appData = guidata(fig);
    frame = appData.currentFrame + 1;
    if frame > appData.nframes
        frame = 1;
    end
    updateTimeFrame(fig, frame);
end

function updateTimeFrame(fig, frame)
    appData = guidata(fig);
    appData.currentFrame = frame;
    if isgraphics(appData.timeSlider)
        appData.timeSlider.Value = frame;
    end
    
    % Update Color Data (Scatter) - Use ABSOLUTE Value for Color intensity (Speed/Magnitude)
    % User requested: "use the colors to represent the flow ... animated the flow itself ... absolute value have sense for this"
    
    rawData = appData.flowPulsatile(:, frame);
    newData = abs(rawData);
    
    set(appData.scatterAll, 'CData', newData);
    
    % Update Colorbar Limits using GLOBAL range (Calculated as Abs Range in init)
    if isfield(appData, 'globalFlowRange')
        caxis(appData.axes, appData.globalFlowRange);
        % Update edit boxes
        appData.cbMinEdit.String = sprintf('%.3f', appData.globalFlowRange(1));
        appData.cbMaxEdit.String = sprintf('%.3f', appData.globalFlowRange(2));
    end
    
    % Update Vectors if visible
    updateVectors(fig);
    
    guidata(fig, appData);
end
